# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.srcs/sources_1/ip/ila_user_xc_inst/ila_user_xc_inst.xci
# IP: The module: 'ila_user_xc_inst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/ila_user_xc_inst/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_user_xc_inst'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/ila_user_xc_inst/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_user_xc_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/ila_user_xc_inst/ila_user_xc_inst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_user_xc_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.srcs/sources_1/ip/ila_user_xc_inst/ila_user_xc_inst.xci
# IP: The module: 'ila_user_xc_inst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/ila_user_xc_inst/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_user_xc_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/ila_user_xc_inst/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_user_xc_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/ila_user_xc_inst/ila_user_xc_inst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_user_xc_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
