#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Mar 12 15:08:44 CST 2025
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim user_xc_inst_tb_behav -key {Behavioral:sim_1:Functional:user_xc_inst_tb} -tclbatch user_xc_inst_tb.tcl -view /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/user_xc_inst_tb_behav.wcfg -log simulate.log"
xsim user_xc_inst_tb_behav -key {Behavioral:sim_1:Functional:user_xc_inst_tb} -tclbatch user_xc_inst_tb.tcl -view /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/user_xc_inst_tb_behav.wcfg -log simulate.log

