//** When the module is full, the threshold is 1000
`default_nettype none
module udma_almost_full #(
    parameter   PROG_FULL_THR   =   900
)(
    //** USER DMA RX INTERFACE FDK
    //!! Connect to User DMA FDK Interface
    output  wire                    fdk_udma_rx_tvalid,
    output  wire    [4:0]           fdk_udma_rx_tuser,
    output  wire                    fdk_udma_rx_tlast,
    output  wire    [255:0]         fdk_udma_rx_tdata,
    output  wire    [31:0]          fdk_udma_rx_tstrb,
    input   wire                    fdk_udma_rx_tready,         //!! Full Signal
    input   wire    [10:0]          fdk_udma_buffer_wr_cnt,     //!! Write Count

    //** USER DMA RX INTERFACE ALMOST FULL
    //!! Connect to User Logic Interface
    input   wire                    userlogic_udma_rx_tvalid,
    input   wire    [4:0]           userlogic_udma_rx_tuser,
    input   wire                    userlogic_udma_rx_tlast,
    input   wire    [255:0]         userlogic_udma_rx_tdata,
    input   wire    [31:0]          userlogic_udma_rx_tstrb,
    output  wire                    userlogic_udma_rx_almost_full //!! Almost Full Signal
);

assign  fdk_udma_rx_tvalid  =   userlogic_udma_rx_tvalid && userlogic_udma_rx_almost_full;
assign  fdk_udma_rx_tuser   =   userlogic_udma_rx_tuser;
assign  fdk_udma_rx_tlast   =   userlogic_udma_rx_tlast;
assign  fdk_udma_rx_tdata   =   userlogic_udma_rx_tdata;
assign  fdk_udma_rx_tstrb   =   userlogic_udma_rx_tstrb;

//** Almost full signal is generated by wrcnt and threshold
assign  userlogic_udma_rx_almost_full  =   fdk_udma_rx_tready && (fdk_udma_buffer_wr_cnt < PROG_FULL_THR);
    
endmodule
`default_nettype wire