# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zhaomj/work/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.srcs/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0.xci
# IP: The module: 'axi_traffic_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhaomj/work/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_traffic_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/zhaomj/work/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_traffic_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/zhaomj/work/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.srcs/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0.xci
# IP: The module: 'axi_traffic_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhaomj/work/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_traffic_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/zhaomj/work/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_traffic_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
