// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module yusur_hash_allocation_Loop_LOOP_OUTPUT_ALL_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        o_axiu_user0_data_TREADY,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        o_axiu_user0_data_TDATA,
        o_axiu_user0_data_TVALID,
        o_axiu_user0_data_TKEEP,
        o_axiu_user0_data_TSTRB,
        o_axiu_user0_data_TLAST,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        p_read50,
        p_read51,
        p_read52,
        p_read53,
        p_read54,
        p_read55,
        p_read56,
        p_read57,
        p_read58,
        p_read59,
        p_read60,
        p_read61,
        p_read62,
        p_read63,
        p_read64,
        p_read65,
        p_read66,
        p_read67,
        p_read68,
        p_read69,
        p_read70,
        p_read71
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   o_axiu_user0_data_TREADY;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
output  [63:0] o_axiu_user0_data_TDATA;
output   o_axiu_user0_data_TVALID;
output  [7:0] o_axiu_user0_data_TKEEP;
output  [7:0] o_axiu_user0_data_TSTRB;
output  [0:0] o_axiu_user0_data_TLAST;
input  [7:0] p_read8;
input  [7:0] p_read9;
input  [7:0] p_read10;
input  [7:0] p_read11;
input  [7:0] p_read12;
input  [7:0] p_read13;
input  [7:0] p_read14;
input  [7:0] p_read15;
input  [7:0] p_read16;
input  [7:0] p_read17;
input  [7:0] p_read18;
input  [7:0] p_read19;
input  [7:0] p_read20;
input  [7:0] p_read21;
input  [7:0] p_read22;
input  [7:0] p_read23;
input  [7:0] p_read24;
input  [7:0] p_read25;
input  [7:0] p_read26;
input  [7:0] p_read27;
input  [7:0] p_read28;
input  [7:0] p_read29;
input  [7:0] p_read30;
input  [7:0] p_read31;
input  [7:0] p_read32;
input  [7:0] p_read33;
input  [7:0] p_read34;
input  [7:0] p_read35;
input  [7:0] p_read36;
input  [7:0] p_read37;
input  [7:0] p_read38;
input  [7:0] p_read39;
input  [7:0] p_read40;
input  [7:0] p_read41;
input  [7:0] p_read42;
input  [7:0] p_read43;
input  [7:0] p_read44;
input  [7:0] p_read45;
input  [7:0] p_read46;
input  [7:0] p_read47;
input  [7:0] p_read48;
input  [7:0] p_read49;
input  [7:0] p_read50;
input  [7:0] p_read51;
input  [7:0] p_read52;
input  [7:0] p_read53;
input  [7:0] p_read54;
input  [7:0] p_read55;
input  [7:0] p_read56;
input  [7:0] p_read57;
input  [7:0] p_read58;
input  [7:0] p_read59;
input  [7:0] p_read60;
input  [7:0] p_read61;
input  [7:0] p_read62;
input  [7:0] p_read63;
input  [7:0] p_read64;
input  [7:0] p_read65;
input  [7:0] p_read66;
input  [7:0] p_read67;
input  [7:0] p_read68;
input  [7:0] p_read69;
input  [7:0] p_read70;
input  [7:0] p_read71;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln114_fu_684_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    o_axiu_user0_data_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] out_val_last_V_fu_696_p2;
reg   [0:0] out_val_last_V_reg_932;
wire   [63:0] out_val_data_V_2_fu_908_p3;
reg   [63:0] out_val_data_V_2_reg_937;
reg   [3:0] i_fu_202;
wire   [3:0] add_ln114_fu_690_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [2:0] trunc_ln132_fu_708_p1;
wire   [7:0] op_assign_7_fu_866_p10;
wire   [7:0] op_assign_6_fu_844_p10;
wire   [7:0] op_assign_5_fu_822_p10;
wire   [7:0] op_assign_4_fu_800_p10;
wire   [7:0] op_assign_3_fu_778_p10;
wire   [7:0] op_assign_2_fu_756_p10;
wire   [7:0] op_assign_1_fu_734_p10;
wire   [7:0] op_assign_fu_712_p10;
wire   [0:0] icmp_ln121_fu_702_p2;
wire   [63:0] or_i15_7_fu_656_p9;
wire   [63:0] out_val_data_V_fu_888_p9;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    o_axiu_user0_data_TVALID_int_regslice;
wire    o_axiu_user0_data_TREADY_int_regslice;
wire    regslice_both_o_axiu_user0_data_V_data_V_U_vld_out;
wire    regslice_both_o_axiu_user0_data_V_keep_V_U_apdone_blk;
wire    regslice_both_o_axiu_user0_data_V_keep_V_U_ack_in_dummy;
wire    regslice_both_o_axiu_user0_data_V_keep_V_U_vld_out;
wire    regslice_both_o_axiu_user0_data_V_strb_V_U_apdone_blk;
wire    regslice_both_o_axiu_user0_data_V_strb_V_U_ack_in_dummy;
wire    regslice_both_o_axiu_user0_data_V_strb_V_U_vld_out;
wire    regslice_both_o_axiu_user0_data_V_last_V_U_apdone_blk;
wire    regslice_both_o_axiu_user0_data_V_last_V_U_ack_in_dummy;
wire    regslice_both_o_axiu_user0_data_V_last_V_U_vld_out;
reg    ap_condition_179;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

yusur_hash_allocation_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U168(
    .din0(p_read8),
    .din1(p_read9),
    .din2(p_read10),
    .din3(p_read11),
    .din4(p_read12),
    .din5(p_read13),
    .din6(p_read14),
    .din7(p_read15),
    .din8(trunc_ln132_fu_708_p1),
    .dout(op_assign_fu_712_p10)
);

yusur_hash_allocation_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U169(
    .din0(p_read16),
    .din1(p_read17),
    .din2(p_read18),
    .din3(p_read19),
    .din4(p_read20),
    .din5(p_read21),
    .din6(p_read22),
    .din7(p_read23),
    .din8(trunc_ln132_fu_708_p1),
    .dout(op_assign_1_fu_734_p10)
);

yusur_hash_allocation_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U170(
    .din0(p_read24),
    .din1(p_read25),
    .din2(p_read26),
    .din3(p_read27),
    .din4(p_read28),
    .din5(p_read29),
    .din6(p_read30),
    .din7(p_read31),
    .din8(trunc_ln132_fu_708_p1),
    .dout(op_assign_2_fu_756_p10)
);

yusur_hash_allocation_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U171(
    .din0(p_read32),
    .din1(p_read33),
    .din2(p_read34),
    .din3(p_read35),
    .din4(p_read36),
    .din5(p_read37),
    .din6(p_read38),
    .din7(p_read39),
    .din8(trunc_ln132_fu_708_p1),
    .dout(op_assign_3_fu_778_p10)
);

yusur_hash_allocation_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U172(
    .din0(p_read40),
    .din1(p_read41),
    .din2(p_read42),
    .din3(p_read43),
    .din4(p_read44),
    .din5(p_read45),
    .din6(p_read46),
    .din7(p_read47),
    .din8(trunc_ln132_fu_708_p1),
    .dout(op_assign_4_fu_800_p10)
);

yusur_hash_allocation_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U173(
    .din0(p_read48),
    .din1(p_read49),
    .din2(p_read50),
    .din3(p_read51),
    .din4(p_read52),
    .din5(p_read53),
    .din6(p_read54),
    .din7(p_read55),
    .din8(trunc_ln132_fu_708_p1),
    .dout(op_assign_5_fu_822_p10)
);

yusur_hash_allocation_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U174(
    .din0(p_read56),
    .din1(p_read57),
    .din2(p_read58),
    .din3(p_read59),
    .din4(p_read60),
    .din5(p_read61),
    .din6(p_read62),
    .din7(p_read63),
    .din8(trunc_ln132_fu_708_p1),
    .dout(op_assign_6_fu_844_p10)
);

yusur_hash_allocation_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U175(
    .din0(p_read64),
    .din1(p_read65),
    .din2(p_read66),
    .din3(p_read67),
    .din4(p_read68),
    .din5(p_read69),
    .din6(p_read70),
    .din7(p_read71),
    .din8(trunc_ln132_fu_708_p1),
    .dout(op_assign_7_fu_866_p10)
);

yusur_hash_allocation_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 64 ))
regslice_both_o_axiu_user0_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_val_data_V_2_reg_937),
    .vld_in(o_axiu_user0_data_TVALID_int_regslice),
    .ack_in(o_axiu_user0_data_TREADY_int_regslice),
    .data_out(o_axiu_user0_data_TDATA),
    .vld_out(regslice_both_o_axiu_user0_data_V_data_V_U_vld_out),
    .ack_out(o_axiu_user0_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 8 ))
regslice_both_o_axiu_user0_data_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(8'd255),
    .vld_in(o_axiu_user0_data_TVALID_int_regslice),
    .ack_in(regslice_both_o_axiu_user0_data_V_keep_V_U_ack_in_dummy),
    .data_out(o_axiu_user0_data_TKEEP),
    .vld_out(regslice_both_o_axiu_user0_data_V_keep_V_U_vld_out),
    .ack_out(o_axiu_user0_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_user0_data_V_keep_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 8 ))
regslice_both_o_axiu_user0_data_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(8'd0),
    .vld_in(o_axiu_user0_data_TVALID_int_regslice),
    .ack_in(regslice_both_o_axiu_user0_data_V_strb_V_U_ack_in_dummy),
    .data_out(o_axiu_user0_data_TSTRB),
    .vld_out(regslice_both_o_axiu_user0_data_V_strb_V_U_vld_out),
    .ack_out(o_axiu_user0_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_user0_data_V_strb_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 1 ))
regslice_both_o_axiu_user0_data_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_val_last_V_reg_932),
    .vld_in(o_axiu_user0_data_TVALID_int_regslice),
    .ack_in(regslice_both_o_axiu_user0_data_V_last_V_U_ack_in_dummy),
    .data_out(o_axiu_user0_data_TLAST),
    .vld_out(regslice_both_o_axiu_user0_data_V_last_V_U_vld_out),
    .ack_out(o_axiu_user0_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_user0_data_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_179)) begin
        if ((icmp_ln114_fu_684_p2 == 1'd0)) begin
            i_fu_202 <= add_ln114_fu_690_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_202 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln114_fu_684_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_val_data_V_2_reg_937 <= out_val_data_V_2_fu_908_p3;
        out_val_last_V_reg_932 <= out_val_last_V_fu_696_p2;
    end
end

always @ (*) begin
    if (((icmp_ln114_fu_684_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_202;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        o_axiu_user0_data_TDATA_blk_n = o_axiu_user0_data_TREADY_int_regslice;
    end else begin
        o_axiu_user0_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        o_axiu_user0_data_TVALID_int_regslice = 1'b1;
    end else begin
        o_axiu_user0_data_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln114_fu_690_p2 = (ap_sig_allocacmp_i_1 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((o_axiu_user0_data_TREADY_int_regslice == 1'b0) | (regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1))) | ((o_axiu_user0_data_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((o_axiu_user0_data_TREADY_int_regslice == 1'b0) | (regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1))) | ((o_axiu_user0_data_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((o_axiu_user0_data_TREADY_int_regslice == 1'b0) | (regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1))) | ((o_axiu_user0_data_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((o_axiu_user0_data_TREADY_int_regslice == 1'b0) | (regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (o_axiu_user0_data_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_condition_179 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln114_fu_684_p2 = ((ap_sig_allocacmp_i_1 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln121_fu_702_p2 = ((ap_sig_allocacmp_i_1 == 4'd0) ? 1'b1 : 1'b0);

assign o_axiu_user0_data_TVALID = regslice_both_o_axiu_user0_data_V_data_V_U_vld_out;

assign or_i15_7_fu_656_p9 = {{{{{{{{p_read}, {p_read1}}, {p_read2}}, {p_read3}}, {p_read4}}, {p_read5}}, {p_read6}}, {p_read7}};

assign out_val_data_V_2_fu_908_p3 = ((icmp_ln121_fu_702_p2[0:0] == 1'b1) ? or_i15_7_fu_656_p9 : out_val_data_V_fu_888_p9);

assign out_val_data_V_fu_888_p9 = {{{{{{{{op_assign_7_fu_866_p10}, {op_assign_6_fu_844_p10}}, {op_assign_5_fu_822_p10}}, {op_assign_4_fu_800_p10}}, {op_assign_3_fu_778_p10}}, {op_assign_2_fu_756_p10}}, {op_assign_1_fu_734_p10}}, {op_assign_fu_712_p10}};

assign out_val_last_V_fu_696_p2 = ((ap_sig_allocacmp_i_1 == 4'd8) ? 1'b1 : 1'b0);

assign trunc_ln132_fu_708_p1 = ap_sig_allocacmp_i_1[2:0];

endmodule //yusur_hash_allocation_Loop_LOOP_OUTPUT_ALL_proc
