// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="yusur_hash_allocation_yusur_hash_allocation,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku15p_CIV-ffve1517-2-e,HLS_INPUT_CLOCK=3.500000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.716000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=1213,HLS_SYN_LUT=4231,HLS_VERSION=2022_2}" *)

module yusur_hash_allocation (
        ap_clk,
        ap_rst_n,
        i_axiu_key_TDATA,
        i_axiu_stream_data_TDATA,
        i_axiu_stream_data_TKEEP,
        i_axiu_stream_data_TSTRB,
        i_axiu_stream_data_TLAST,
        i_axiu_user0_data_TDATA,
        i_axiu_user0_data_TKEEP,
        i_axiu_user0_data_TSTRB,
        i_axiu_user0_data_TLAST,
        o_axiu_user0_data_TDATA,
        o_axiu_user0_data_TKEEP,
        o_axiu_user0_data_TSTRB,
        o_axiu_user0_data_TLAST,
        i_axiu_key_TVALID,
        i_axiu_key_TREADY,
        i_axiu_stream_data_TVALID,
        i_axiu_stream_data_TREADY,
        i_axiu_user0_data_TVALID,
        i_axiu_user0_data_TREADY,
        o_axiu_user0_data_TVALID,
        o_axiu_user0_data_TREADY
);


input   ap_clk;
input   ap_rst_n;
input  [79:0] i_axiu_key_TDATA;
input  [63:0] i_axiu_stream_data_TDATA;
input  [7:0] i_axiu_stream_data_TKEEP;
input  [7:0] i_axiu_stream_data_TSTRB;
input  [0:0] i_axiu_stream_data_TLAST;
input  [63:0] i_axiu_user0_data_TDATA;
input  [7:0] i_axiu_user0_data_TKEEP;
input  [7:0] i_axiu_user0_data_TSTRB;
input  [0:0] i_axiu_user0_data_TLAST;
output  [63:0] o_axiu_user0_data_TDATA;
output  [7:0] o_axiu_user0_data_TKEEP;
output  [7:0] o_axiu_user0_data_TSTRB;
output  [0:0] o_axiu_user0_data_TLAST;
input   i_axiu_key_TVALID;
output   i_axiu_key_TREADY;
input   i_axiu_stream_data_TVALID;
output   i_axiu_stream_data_TREADY;
input   i_axiu_user0_data_TVALID;
output   i_axiu_user0_data_TREADY;
output   o_axiu_user0_data_TVALID;
input   o_axiu_user0_data_TREADY;

 reg    ap_rst_n_inv;
wire   [7:0] C_MATRIX_i_q0;
wire   [7:0] C_MATRIX_t_q0;
wire   [63:0] batch_data_out_V_i_q0;
wire   [63:0] batch_data_out_V_t_q0;
wire   [7:0] keep_data_out_V_i_q0;
wire   [7:0] keep_data_out_V_t_q0;
wire   [0:0] last_data_out_V_i_q0;
wire   [0:0] last_data_out_V_t_q0;
wire    Block_entry19_proc3_U0_ap_start;
wire    Block_entry19_proc3_U0_ap_done;
wire    Block_entry19_proc3_U0_ap_continue;
wire    Block_entry19_proc3_U0_ap_idle;
wire    Block_entry19_proc3_U0_ap_ready;
wire   [6:0] Block_entry19_proc3_U0_C_MATRIX_address0;
wire    Block_entry19_proc3_U0_C_MATRIX_ce0;
wire    Block_entry19_proc3_U0_C_MATRIX_we0;
wire   [7:0] Block_entry19_proc3_U0_C_MATRIX_d0;
wire   [6:0] Block_entry19_proc3_U0_C_MATRIX_address1;
wire    Block_entry19_proc3_U0_C_MATRIX_ce1;
wire    Block_entry19_proc3_U0_C_MATRIX_we1;
wire   [7:0] Block_entry19_proc3_U0_C_MATRIX_d1;
wire    Block_entry19_proc3_U0_i_axiu_key_TREADY;
wire    Block_entry19_proc3_U0_i_axiu_stream_data_TREADY;
wire    Block_entry19_proc3_U0_i_axiu_user0_data_TREADY;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_ap_start;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_ap_done;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_ap_continue;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_ap_idle;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_ap_ready;
wire   [6:0] Loop_LOOP_PACK_OUTPUT_proc_U0_C_MATRIX_address0;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_C_MATRIX_ce0;
wire   [7:0] Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_address0;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_ce0;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_we0;
wire   [63:0] Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_d0;
wire   [7:0] Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_address0;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_ce0;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_we0;
wire   [7:0] Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_d0;
wire   [7:0] Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_address0;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_ce0;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_we0;
wire   [0:0] Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_d0;
wire   [31:0] Loop_LOOP_PACK_OUTPUT_proc_U0_ap_return;
wire    ap_channel_done_pkt_len_out_3_loc_channel1;
wire    pkt_len_out_3_loc_channel1_full_n;
reg    ap_sync_reg_channel_write_pkt_len_out_3_loc_channel1;
wire    ap_sync_channel_write_pkt_len_out_3_loc_channel1;
wire    ap_channel_done_last_data_out_V;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_full_n;
reg    ap_sync_reg_channel_write_last_data_out_V;
wire    ap_sync_channel_write_last_data_out_V;
wire    ap_channel_done_keep_data_out_V;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_full_n;
reg    ap_sync_reg_channel_write_keep_data_out_V;
wire    ap_sync_channel_write_keep_data_out_V;
wire    ap_channel_done_batch_data_out_V;
wire    Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_full_n;
reg    ap_sync_reg_channel_write_batch_data_out_V;
wire    ap_sync_channel_write_batch_data_out_V;
wire    Loop_LOOP_FORWARD_proc_U0_ap_start;
wire    Loop_LOOP_FORWARD_proc_U0_ap_done;
wire    Loop_LOOP_FORWARD_proc_U0_ap_continue;
wire    Loop_LOOP_FORWARD_proc_U0_ap_idle;
wire    Loop_LOOP_FORWARD_proc_U0_ap_ready;
wire   [7:0] Loop_LOOP_FORWARD_proc_U0_batch_data_out_V_address0;
wire    Loop_LOOP_FORWARD_proc_U0_batch_data_out_V_ce0;
wire   [7:0] Loop_LOOP_FORWARD_proc_U0_keep_data_out_V_address0;
wire    Loop_LOOP_FORWARD_proc_U0_keep_data_out_V_ce0;
wire   [7:0] Loop_LOOP_FORWARD_proc_U0_last_data_out_V_address0;
wire    Loop_LOOP_FORWARD_proc_U0_last_data_out_V_ce0;
wire   [63:0] Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TDATA;
wire    Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TVALID;
wire   [7:0] Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TKEEP;
wire   [7:0] Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TSTRB;
wire   [0:0] Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TLAST;
wire    C_MATRIX_i_full_n;
wire    C_MATRIX_t_empty_n;
wire    batch_data_out_V_i_full_n;
wire    batch_data_out_V_t_empty_n;
wire    keep_data_out_V_i_full_n;
wire    keep_data_out_V_t_empty_n;
wire    last_data_out_V_i_full_n;
wire    last_data_out_V_t_empty_n;
wire   [31:0] pkt_len_out_3_loc_channel1_dout;
wire   [1:0] pkt_len_out_3_loc_channel1_num_data_valid;
wire   [1:0] pkt_len_out_3_loc_channel1_fifo_cap;
wire    pkt_len_out_3_loc_channel1_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_pkt_len_out_3_loc_channel1 = 1'b0;
#0 ap_sync_reg_channel_write_last_data_out_V = 1'b0;
#0 ap_sync_reg_channel_write_keep_data_out_V = 1'b0;
#0 ap_sync_reg_channel_write_batch_data_out_V = 1'b0;
end

yusur_hash_allocation_C_MATRIX_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 81 ),
    .AddressWidth( 7 ))
C_MATRIX_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_entry19_proc3_U0_C_MATRIX_address0),
    .i_ce0(Block_entry19_proc3_U0_C_MATRIX_ce0),
    .i_we0(Block_entry19_proc3_U0_C_MATRIX_we0),
    .i_d0(Block_entry19_proc3_U0_C_MATRIX_d0),
    .i_q0(C_MATRIX_i_q0),
    .i_address1(Block_entry19_proc3_U0_C_MATRIX_address1),
    .i_ce1(Block_entry19_proc3_U0_C_MATRIX_ce1),
    .i_we1(Block_entry19_proc3_U0_C_MATRIX_we1),
    .i_d1(Block_entry19_proc3_U0_C_MATRIX_d1),
    .t_address0(Loop_LOOP_PACK_OUTPUT_proc_U0_C_MATRIX_address0),
    .t_ce0(Loop_LOOP_PACK_OUTPUT_proc_U0_C_MATRIX_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(C_MATRIX_t_q0),
    .t_address1(7'd0),
    .t_ce1(1'b0),
    .t_we1(1'b0),
    .t_d1(8'd0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(C_MATRIX_i_full_n),
    .i_write(Block_entry19_proc3_U0_ap_done),
    .t_empty_n(C_MATRIX_t_empty_n),
    .t_read(Loop_LOOP_PACK_OUTPUT_proc_U0_ap_ready)
);

yusur_hash_allocation_batch_data_out_V_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
batch_data_out_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_address0),
    .i_ce0(Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_ce0),
    .i_we0(Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_we0),
    .i_d0(Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_d0),
    .i_q0(batch_data_out_V_i_q0),
    .t_address0(Loop_LOOP_FORWARD_proc_U0_batch_data_out_V_address0),
    .t_ce0(Loop_LOOP_FORWARD_proc_U0_batch_data_out_V_ce0),
    .t_we0(1'b0),
    .t_d0(64'd0),
    .t_q0(batch_data_out_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(batch_data_out_V_i_full_n),
    .i_write(ap_channel_done_batch_data_out_V),
    .t_empty_n(batch_data_out_V_t_empty_n),
    .t_read(Loop_LOOP_FORWARD_proc_U0_ap_ready)
);

yusur_hash_allocation_keep_data_out_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
keep_data_out_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_address0),
    .i_ce0(Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_ce0),
    .i_we0(Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_we0),
    .i_d0(Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_d0),
    .i_q0(keep_data_out_V_i_q0),
    .t_address0(Loop_LOOP_FORWARD_proc_U0_keep_data_out_V_address0),
    .t_ce0(Loop_LOOP_FORWARD_proc_U0_keep_data_out_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(keep_data_out_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(keep_data_out_V_i_full_n),
    .i_write(ap_channel_done_keep_data_out_V),
    .t_empty_n(keep_data_out_V_t_empty_n),
    .t_read(Loop_LOOP_FORWARD_proc_U0_ap_ready)
);

yusur_hash_allocation_last_data_out_V_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
last_data_out_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_address0),
    .i_ce0(Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_ce0),
    .i_we0(Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_we0),
    .i_d0(Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_d0),
    .i_q0(last_data_out_V_i_q0),
    .t_address0(Loop_LOOP_FORWARD_proc_U0_last_data_out_V_address0),
    .t_ce0(Loop_LOOP_FORWARD_proc_U0_last_data_out_V_ce0),
    .t_we0(1'b0),
    .t_d0(1'd0),
    .t_q0(last_data_out_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(last_data_out_V_i_full_n),
    .i_write(ap_channel_done_last_data_out_V),
    .t_empty_n(last_data_out_V_t_empty_n),
    .t_read(Loop_LOOP_FORWARD_proc_U0_ap_ready)
);

yusur_hash_allocation_Block_entry19_proc3 Block_entry19_proc3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry19_proc3_U0_ap_start),
    .ap_done(Block_entry19_proc3_U0_ap_done),
    .ap_continue(Block_entry19_proc3_U0_ap_continue),
    .ap_idle(Block_entry19_proc3_U0_ap_idle),
    .ap_ready(Block_entry19_proc3_U0_ap_ready),
    .C_MATRIX_address0(Block_entry19_proc3_U0_C_MATRIX_address0),
    .C_MATRIX_ce0(Block_entry19_proc3_U0_C_MATRIX_ce0),
    .C_MATRIX_we0(Block_entry19_proc3_U0_C_MATRIX_we0),
    .C_MATRIX_d0(Block_entry19_proc3_U0_C_MATRIX_d0),
    .C_MATRIX_address1(Block_entry19_proc3_U0_C_MATRIX_address1),
    .C_MATRIX_ce1(Block_entry19_proc3_U0_C_MATRIX_ce1),
    .C_MATRIX_we1(Block_entry19_proc3_U0_C_MATRIX_we1),
    .C_MATRIX_d1(Block_entry19_proc3_U0_C_MATRIX_d1),
    .i_axiu_key_TDATA(i_axiu_key_TDATA),
    .i_axiu_key_TVALID(i_axiu_key_TVALID),
    .i_axiu_key_TREADY(Block_entry19_proc3_U0_i_axiu_key_TREADY),
    .i_axiu_stream_data_TDATA(i_axiu_stream_data_TDATA),
    .i_axiu_stream_data_TVALID(i_axiu_stream_data_TVALID),
    .i_axiu_stream_data_TREADY(Block_entry19_proc3_U0_i_axiu_stream_data_TREADY),
    .i_axiu_stream_data_TKEEP(i_axiu_stream_data_TKEEP),
    .i_axiu_stream_data_TSTRB(i_axiu_stream_data_TSTRB),
    .i_axiu_stream_data_TLAST(i_axiu_stream_data_TLAST),
    .i_axiu_user0_data_TDATA(i_axiu_user0_data_TDATA),
    .i_axiu_user0_data_TVALID(i_axiu_user0_data_TVALID),
    .i_axiu_user0_data_TREADY(Block_entry19_proc3_U0_i_axiu_user0_data_TREADY),
    .i_axiu_user0_data_TKEEP(i_axiu_user0_data_TKEEP),
    .i_axiu_user0_data_TSTRB(i_axiu_user0_data_TSTRB),
    .i_axiu_user0_data_TLAST(i_axiu_user0_data_TLAST)
);

yusur_hash_allocation_Loop_LOOP_PACK_OUTPUT_proc Loop_LOOP_PACK_OUTPUT_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_LOOP_PACK_OUTPUT_proc_U0_ap_start),
    .ap_done(Loop_LOOP_PACK_OUTPUT_proc_U0_ap_done),
    .ap_continue(Loop_LOOP_PACK_OUTPUT_proc_U0_ap_continue),
    .ap_idle(Loop_LOOP_PACK_OUTPUT_proc_U0_ap_idle),
    .ap_ready(Loop_LOOP_PACK_OUTPUT_proc_U0_ap_ready),
    .C_MATRIX_address0(Loop_LOOP_PACK_OUTPUT_proc_U0_C_MATRIX_address0),
    .C_MATRIX_ce0(Loop_LOOP_PACK_OUTPUT_proc_U0_C_MATRIX_ce0),
    .C_MATRIX_q0(C_MATRIX_t_q0),
    .batch_data_out_V_address0(Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_address0),
    .batch_data_out_V_ce0(Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_ce0),
    .batch_data_out_V_we0(Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_we0),
    .batch_data_out_V_d0(Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_d0),
    .keep_data_out_V_address0(Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_address0),
    .keep_data_out_V_ce0(Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_ce0),
    .keep_data_out_V_we0(Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_we0),
    .keep_data_out_V_d0(Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_d0),
    .last_data_out_V_address0(Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_address0),
    .last_data_out_V_ce0(Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_ce0),
    .last_data_out_V_we0(Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_we0),
    .last_data_out_V_d0(Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_d0),
    .ap_return(Loop_LOOP_PACK_OUTPUT_proc_U0_ap_return)
);

yusur_hash_allocation_Loop_LOOP_FORWARD_proc Loop_LOOP_FORWARD_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_LOOP_FORWARD_proc_U0_ap_start),
    .ap_done(Loop_LOOP_FORWARD_proc_U0_ap_done),
    .ap_continue(Loop_LOOP_FORWARD_proc_U0_ap_continue),
    .ap_idle(Loop_LOOP_FORWARD_proc_U0_ap_idle),
    .ap_ready(Loop_LOOP_FORWARD_proc_U0_ap_ready),
    .o_axiu_user0_data_TREADY(o_axiu_user0_data_TREADY),
    .p_read(pkt_len_out_3_loc_channel1_dout),
    .batch_data_out_V_address0(Loop_LOOP_FORWARD_proc_U0_batch_data_out_V_address0),
    .batch_data_out_V_ce0(Loop_LOOP_FORWARD_proc_U0_batch_data_out_V_ce0),
    .batch_data_out_V_q0(batch_data_out_V_t_q0),
    .keep_data_out_V_address0(Loop_LOOP_FORWARD_proc_U0_keep_data_out_V_address0),
    .keep_data_out_V_ce0(Loop_LOOP_FORWARD_proc_U0_keep_data_out_V_ce0),
    .keep_data_out_V_q0(keep_data_out_V_t_q0),
    .last_data_out_V_address0(Loop_LOOP_FORWARD_proc_U0_last_data_out_V_address0),
    .last_data_out_V_ce0(Loop_LOOP_FORWARD_proc_U0_last_data_out_V_ce0),
    .last_data_out_V_q0(last_data_out_V_t_q0),
    .o_axiu_user0_data_TDATA(Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TDATA),
    .o_axiu_user0_data_TVALID(Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TVALID),
    .o_axiu_user0_data_TKEEP(Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TKEEP),
    .o_axiu_user0_data_TSTRB(Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TSTRB),
    .o_axiu_user0_data_TLAST(Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TLAST)
);

yusur_hash_allocation_fifo_w32_d2_S pkt_len_out_3_loc_channel1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_LOOP_PACK_OUTPUT_proc_U0_ap_return),
    .if_full_n(pkt_len_out_3_loc_channel1_full_n),
    .if_write(ap_channel_done_pkt_len_out_3_loc_channel1),
    .if_dout(pkt_len_out_3_loc_channel1_dout),
    .if_num_data_valid(pkt_len_out_3_loc_channel1_num_data_valid),
    .if_fifo_cap(pkt_len_out_3_loc_channel1_fifo_cap),
    .if_empty_n(pkt_len_out_3_loc_channel1_empty_n),
    .if_read(Loop_LOOP_FORWARD_proc_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_batch_data_out_V <= 1'b0;
    end else begin
        if (((Loop_LOOP_PACK_OUTPUT_proc_U0_ap_done & Loop_LOOP_PACK_OUTPUT_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_batch_data_out_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_batch_data_out_V <= ap_sync_channel_write_batch_data_out_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_keep_data_out_V <= 1'b0;
    end else begin
        if (((Loop_LOOP_PACK_OUTPUT_proc_U0_ap_done & Loop_LOOP_PACK_OUTPUT_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_keep_data_out_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_keep_data_out_V <= ap_sync_channel_write_keep_data_out_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_last_data_out_V <= 1'b0;
    end else begin
        if (((Loop_LOOP_PACK_OUTPUT_proc_U0_ap_done & Loop_LOOP_PACK_OUTPUT_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_last_data_out_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_last_data_out_V <= ap_sync_channel_write_last_data_out_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_pkt_len_out_3_loc_channel1 <= 1'b0;
    end else begin
        if (((Loop_LOOP_PACK_OUTPUT_proc_U0_ap_done & Loop_LOOP_PACK_OUTPUT_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_pkt_len_out_3_loc_channel1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_pkt_len_out_3_loc_channel1 <= ap_sync_channel_write_pkt_len_out_3_loc_channel1;
        end
    end
end

assign Block_entry19_proc3_U0_ap_continue = C_MATRIX_i_full_n;

assign Block_entry19_proc3_U0_ap_start = 1'b1;

assign Loop_LOOP_FORWARD_proc_U0_ap_continue = 1'b1;

assign Loop_LOOP_FORWARD_proc_U0_ap_start = (pkt_len_out_3_loc_channel1_empty_n & last_data_out_V_t_empty_n & keep_data_out_V_t_empty_n & batch_data_out_V_t_empty_n);

assign Loop_LOOP_PACK_OUTPUT_proc_U0_ap_continue = (ap_sync_channel_write_pkt_len_out_3_loc_channel1 & ap_sync_channel_write_last_data_out_V & ap_sync_channel_write_keep_data_out_V & ap_sync_channel_write_batch_data_out_V);

assign Loop_LOOP_PACK_OUTPUT_proc_U0_ap_start = C_MATRIX_t_empty_n;

assign Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_full_n = batch_data_out_V_i_full_n;

assign Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_full_n = keep_data_out_V_i_full_n;

assign Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_full_n = last_data_out_V_i_full_n;

assign ap_channel_done_batch_data_out_V = ((ap_sync_reg_channel_write_batch_data_out_V ^ 1'b1) & Loop_LOOP_PACK_OUTPUT_proc_U0_ap_done);

assign ap_channel_done_keep_data_out_V = ((ap_sync_reg_channel_write_keep_data_out_V ^ 1'b1) & Loop_LOOP_PACK_OUTPUT_proc_U0_ap_done);

assign ap_channel_done_last_data_out_V = ((ap_sync_reg_channel_write_last_data_out_V ^ 1'b1) & Loop_LOOP_PACK_OUTPUT_proc_U0_ap_done);

assign ap_channel_done_pkt_len_out_3_loc_channel1 = ((ap_sync_reg_channel_write_pkt_len_out_3_loc_channel1 ^ 1'b1) & Loop_LOOP_PACK_OUTPUT_proc_U0_ap_done);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_batch_data_out_V = ((ap_channel_done_batch_data_out_V & Loop_LOOP_PACK_OUTPUT_proc_U0_batch_data_out_V_full_n) | ap_sync_reg_channel_write_batch_data_out_V);

assign ap_sync_channel_write_keep_data_out_V = ((ap_channel_done_keep_data_out_V & Loop_LOOP_PACK_OUTPUT_proc_U0_keep_data_out_V_full_n) | ap_sync_reg_channel_write_keep_data_out_V);

assign ap_sync_channel_write_last_data_out_V = ((ap_channel_done_last_data_out_V & Loop_LOOP_PACK_OUTPUT_proc_U0_last_data_out_V_full_n) | ap_sync_reg_channel_write_last_data_out_V);

assign ap_sync_channel_write_pkt_len_out_3_loc_channel1 = ((pkt_len_out_3_loc_channel1_full_n & ap_channel_done_pkt_len_out_3_loc_channel1) | ap_sync_reg_channel_write_pkt_len_out_3_loc_channel1);

assign i_axiu_key_TREADY = Block_entry19_proc3_U0_i_axiu_key_TREADY;

assign i_axiu_stream_data_TREADY = Block_entry19_proc3_U0_i_axiu_stream_data_TREADY;

assign i_axiu_user0_data_TREADY = Block_entry19_proc3_U0_i_axiu_user0_data_TREADY;

assign o_axiu_user0_data_TDATA = Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TDATA;

assign o_axiu_user0_data_TKEEP = Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TKEEP;

assign o_axiu_user0_data_TLAST = Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TLAST;

assign o_axiu_user0_data_TSTRB = Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TSTRB;

assign o_axiu_user0_data_TVALID = Loop_LOOP_FORWARD_proc_U0_o_axiu_user0_data_TVALID;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "yusur_hash_allocation_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "yusur_hash_allocation_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //yusur_hash_allocation

