// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module yusur_hash_allocation_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        C_MATRIX_address0,
        C_MATRIX_ce0,
        C_MATRIX_we0,
        C_MATRIX_d0,
        A_MATRIX_address0,
        A_MATRIX_ce0,
        A_MATRIX_q0,
        B_MATRIX_address0,
        B_MATRIX_ce0,
        B_MATRIX_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] C_MATRIX_address0;
output   C_MATRIX_ce0;
output   C_MATRIX_we0;
output  [7:0] C_MATRIX_d0;
output  [6:0] A_MATRIX_address0;
output   A_MATRIX_ce0;
input  [7:0] A_MATRIX_q0;
output  [6:0] B_MATRIX_address0;
output   B_MATRIX_ce0;
input  [7:0] B_MATRIX_q0;

reg ap_idle;
reg C_MATRIX_ce0;
reg C_MATRIX_we0;
reg A_MATRIX_ce0;
reg B_MATRIX_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln187_fu_125_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln187_reg_264;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln187_reg_264_pp0_iter1_reg;
reg   [0:0] icmp_ln187_reg_264_pp0_iter2_reg;
reg   [0:0] icmp_ln187_reg_264_pp0_iter3_reg;
wire   [6:0] add_ln191_1_fu_193_p2;
reg   [6:0] add_ln191_1_reg_268;
reg   [6:0] C_MATRIX_addr_reg_273;
reg   [6:0] C_MATRIX_addr_reg_273_pp0_iter2_reg;
reg   [6:0] C_MATRIX_addr_reg_273_pp0_iter3_reg;
reg   [6:0] B_MATRIX_addr_reg_283;
reg  signed [7:0] A_MATRIX_load_reg_288;
wire   [0:0] icmp_ln190_fu_226_p2;
reg   [0:0] icmp_ln190_reg_293;
reg   [0:0] icmp_ln190_reg_293_pp0_iter3_reg;
wire   [0:0] icmp_ln190_1_fu_232_p2;
reg   [0:0] icmp_ln190_1_reg_297;
wire   [7:0] mul_ln191_fu_238_p2;
reg   [7:0] mul_ln191_reg_301;
reg   [7:0] ap_phi_mux_storemerge_phi_fu_99_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_storemerge_reg_95;
reg   [7:0] ap_phi_reg_pp0_iter1_storemerge_reg_95;
reg   [7:0] ap_phi_reg_pp0_iter2_storemerge_reg_95;
reg   [7:0] ap_phi_reg_pp0_iter3_storemerge_reg_95;
reg   [7:0] ap_phi_reg_pp0_iter4_storemerge_reg_95;
wire   [63:0] zext_ln191_2_fu_220_p1;
wire    ap_block_pp0_stage0;
reg   [3:0] j_fu_46;
wire   [3:0] add_ln188_fu_199_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_load;
reg   [3:0] i_1_fu_50;
wire   [3:0] select_ln187_1_fu_163_p3;
reg   [3:0] ap_sig_allocacmp_i_1_load;
reg   [6:0] indvar_flatten8_fu_54;
wire   [6:0] add_ln187_1_fu_131_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten8_load;
wire   [0:0] icmp_ln188_fu_149_p2;
wire   [3:0] add_ln187_fu_143_p2;
wire   [6:0] tmp_3_fu_175_p3;
wire   [6:0] zext_ln191_fu_171_p1;
wire   [3:0] select_ln187_fu_155_p3;
wire   [6:0] add_ln191_fu_183_p2;
wire   [6:0] zext_ln191_1_fu_189_p1;
wire  signed [7:0] icmp_ln190_fu_226_p0;
wire  signed [7:0] icmp_ln190_1_fu_232_p0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_144;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

yusur_hash_allocation_mul_8s_8s_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mul_8s_8s_8_1_1_U17(
    .din0(B_MATRIX_q0),
    .din1(A_MATRIX_load_reg_288),
    .dout(mul_ln191_fu_238_p2)
);

yusur_hash_allocation_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((1'b1 == ap_condition_144)) begin
            ap_phi_reg_pp0_iter4_storemerge_reg_95 <= 8'd254;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_storemerge_reg_95 <= ap_phi_reg_pp0_iter3_storemerge_reg_95;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln187_fu_125_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_50 <= select_ln187_1_fu_163_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_50 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln187_fu_125_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten8_fu_54 <= add_ln187_1_fu_131_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten8_fu_54 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln187_fu_125_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_46 <= add_ln188_fu_199_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_46 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln187_reg_264_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_MATRIX_load_reg_288 <= A_MATRIX_q0;
        icmp_ln190_reg_293 <= icmp_ln190_fu_226_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln187_reg_264 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_MATRIX_addr_reg_283 <= zext_ln191_2_fu_220_p1;
        C_MATRIX_addr_reg_273 <= zext_ln191_2_fu_220_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        C_MATRIX_addr_reg_273_pp0_iter2_reg <= C_MATRIX_addr_reg_273;
        C_MATRIX_addr_reg_273_pp0_iter3_reg <= C_MATRIX_addr_reg_273_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln187_reg_264_pp0_iter2_reg <= icmp_ln187_reg_264_pp0_iter1_reg;
        icmp_ln187_reg_264_pp0_iter3_reg <= icmp_ln187_reg_264_pp0_iter2_reg;
        icmp_ln190_reg_293_pp0_iter3_reg <= icmp_ln190_reg_293;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln187_fu_125_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln191_1_reg_268 <= add_ln191_1_fu_193_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln187_reg_264 <= icmp_ln187_fu_125_p2;
        icmp_ln187_reg_264_pp0_iter1_reg <= icmp_ln187_reg_264;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_storemerge_reg_95 <= ap_phi_reg_pp0_iter0_storemerge_reg_95;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_storemerge_reg_95 <= ap_phi_reg_pp0_iter1_storemerge_reg_95;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_storemerge_reg_95 <= ap_phi_reg_pp0_iter2_storemerge_reg_95;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln187_reg_264_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln190_reg_293 == 1'd1))) begin
        icmp_ln190_1_reg_297 <= icmp_ln190_1_fu_232_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln187_reg_264_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln190_1_fu_232_p2 == 1'd1) & (icmp_ln190_reg_293 == 1'd1))) begin
        mul_ln191_reg_301 <= mul_ln191_fu_238_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_MATRIX_ce0 = 1'b1;
    end else begin
        A_MATRIX_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_MATRIX_ce0 = 1'b1;
    end else begin
        B_MATRIX_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        C_MATRIX_ce0 = 1'b1;
    end else begin
        C_MATRIX_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        C_MATRIX_we0 = 1'b1;
    end else begin
        C_MATRIX_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln187_fu_125_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln187_reg_264_pp0_iter3_reg == 1'd0) & (icmp_ln190_1_reg_297 == 1'd1) & (icmp_ln190_reg_293_pp0_iter3_reg == 1'd1))) begin
        ap_phi_mux_storemerge_phi_fu_99_p4 = mul_ln191_reg_301;
    end else begin
        ap_phi_mux_storemerge_phi_fu_99_p4 = ap_phi_reg_pp0_iter4_storemerge_reg_95;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1_load = i_1_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten8_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten8_load = indvar_flatten8_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_46;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_MATRIX_address0 = zext_ln191_2_fu_220_p1;

assign B_MATRIX_address0 = B_MATRIX_addr_reg_283;

assign C_MATRIX_address0 = C_MATRIX_addr_reg_273_pp0_iter3_reg;

assign C_MATRIX_d0 = ap_phi_mux_storemerge_phi_fu_99_p4;

assign add_ln187_1_fu_131_p2 = (ap_sig_allocacmp_indvar_flatten8_load + 7'd1);

assign add_ln187_fu_143_p2 = (ap_sig_allocacmp_i_1_load + 4'd1);

assign add_ln188_fu_199_p2 = (select_ln187_fu_155_p3 + 4'd1);

assign add_ln191_1_fu_193_p2 = (add_ln191_fu_183_p2 + zext_ln191_1_fu_189_p1);

assign add_ln191_fu_183_p2 = (tmp_3_fu_175_p3 + zext_ln191_fu_171_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_144 = (((icmp_ln187_reg_264_pp0_iter2_reg == 1'd0) & (icmp_ln190_reg_293 == 1'd0)) | ((icmp_ln187_reg_264_pp0_iter2_reg == 1'd0) & (icmp_ln190_1_fu_232_p2 == 1'd0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storemerge_reg_95 = 'bx;

assign icmp_ln187_fu_125_p2 = ((ap_sig_allocacmp_indvar_flatten8_load == 7'd81) ? 1'b1 : 1'b0);

assign icmp_ln188_fu_149_p2 = ((ap_sig_allocacmp_j_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln190_1_fu_232_p0 = B_MATRIX_q0;

assign icmp_ln190_1_fu_232_p2 = ((icmp_ln190_1_fu_232_p0 < 8'd254) ? 1'b1 : 1'b0);

assign icmp_ln190_fu_226_p0 = A_MATRIX_q0;

assign icmp_ln190_fu_226_p2 = ((icmp_ln190_fu_226_p0 < 8'd254) ? 1'b1 : 1'b0);

assign select_ln187_1_fu_163_p3 = ((icmp_ln188_fu_149_p2[0:0] == 1'b1) ? add_ln187_fu_143_p2 : ap_sig_allocacmp_i_1_load);

assign select_ln187_fu_155_p3 = ((icmp_ln188_fu_149_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j_load);

assign tmp_3_fu_175_p3 = {{select_ln187_1_fu_163_p3}, {3'd0}};

assign zext_ln191_1_fu_189_p1 = select_ln187_fu_155_p3;

assign zext_ln191_2_fu_220_p1 = add_ln191_1_reg_268;

assign zext_ln191_fu_171_p1 = select_ln187_1_fu_163_p3;

endmodule //yusur_hash_allocation_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5
