// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module yusur_hash_allocation_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln140,
        batch_data_V_address0,
        batch_data_V_ce0,
        batch_data_V_q0,
        keep_data_V_address0,
        keep_data_V_ce0,
        keep_data_V_q0,
        A_MATRIX_address0,
        A_MATRIX_ce0,
        A_MATRIX_we0,
        A_MATRIX_d0,
        B_MATRIX_address0,
        B_MATRIX_ce0,
        B_MATRIX_we0,
        B_MATRIX_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [34:0] zext_ln140;
output  [7:0] batch_data_V_address0;
output   batch_data_V_ce0;
input  [63:0] batch_data_V_q0;
output  [7:0] keep_data_V_address0;
output   keep_data_V_ce0;
input  [7:0] keep_data_V_q0;
output  [6:0] A_MATRIX_address0;
output   A_MATRIX_ce0;
output   A_MATRIX_we0;
output  [7:0] A_MATRIX_d0;
output  [6:0] B_MATRIX_address0;
output   B_MATRIX_ce0;
output   B_MATRIX_we0;
output  [7:0] B_MATRIX_d0;

reg ap_idle;
reg batch_data_V_ce0;
reg keep_data_V_ce0;
reg[6:0] A_MATRIX_address0;
reg A_MATRIX_ce0;
reg A_MATRIX_we0;
reg[7:0] A_MATRIX_d0;
reg[6:0] B_MATRIX_address0;
reg B_MATRIX_ce0;
reg B_MATRIX_we0;
reg[7:0] B_MATRIX_d0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln140_fu_219_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln140_reg_572;
reg   [0:0] icmp_ln140_reg_572_pp0_iter2_reg;
reg   [0:0] icmp_ln140_reg_572_pp0_iter3_reg;
wire   [30:0] select_ln140_1_fu_256_p3;
reg   [30:0] select_ln140_1_reg_576;
wire   [2:0] trunc_ln1669_fu_264_p1;
reg   [2:0] trunc_ln1669_reg_581;
reg   [2:0] trunc_ln1669_reg_581_pp0_iter2_reg;
reg   [2:0] trunc_ln1669_reg_581_pp0_iter3_reg;
reg   [63:0] batch_data_V_load_reg_597;
wire   [0:0] r_V_fu_303_p1;
reg   [0:0] r_V_reg_602;
wire   [63:0] zext_ln140_1_fu_289_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln164_fu_370_p1;
wire   [7:0] val_fu_336_p1;
wire   [0:0] grp_fu_159_p2;
wire   [0:0] grp_fu_175_p2;
wire   [63:0] zext_ln162_fu_403_p1;
wire   [63:0] zext_ln177_fu_467_p1;
wire   [63:0] zext_ln172_fu_510_p1;
reg   [3:0] b_fu_56;
wire   [3:0] add_ln148_fu_268_p2;
wire    ap_loop_init;
reg   [30:0] i_fu_60;
reg   [34:0] indvar_flatten_fu_64;
wire   [34:0] add_ln140_fu_224_p2;
reg   [31:0] r_fu_68;
wire   [31:0] r_3_fu_408_p2;
reg   [31:0] m_idx_fu_72;
reg   [31:0] c_fu_76;
wire   [31:0] grp_fu_181_p2;
wire   [0:0] grp_fu_165_p2;
wire   [0:0] grp_fu_170_p2;
wire   [0:0] icmp_ln148_fu_242_p2;
wire   [30:0] add_ln145_fu_236_p2;
wire   [3:0] select_ln140_fu_248_p3;
wire   [7:0] zext_ln1669_fu_294_p1;
wire   [7:0] lshr_ln1669_fu_297_p2;
wire   [5:0] shl_ln_fu_320_p3;
wire   [63:0] zext_ln1669_2_fu_327_p1;
wire   [63:0] r_V_1_fu_331_p2;
wire   [3:0] trunc_ln145_fu_316_p1;
wire   [6:0] tmp_7_fu_350_p3;
wire   [6:0] trunc_ln164_1_fu_346_p1;
wire   [6:0] add_ln164_fu_358_p2;
wire   [6:0] trunc_ln164_fu_342_p1;
wire   [6:0] add_ln164_1_fu_364_p2;
wire   [6:0] tmp_6_fu_383_p3;
wire   [6:0] trunc_ln162_1_fu_379_p1;
wire   [6:0] add_ln162_fu_391_p2;
wire   [6:0] trunc_ln162_fu_375_p1;
wire   [6:0] add_ln162_1_fu_397_p2;
wire   [6:0] tmp_5_fu_447_p3;
wire   [6:0] trunc_ln177_1_fu_443_p1;
wire   [6:0] add_ln177_fu_455_p2;
wire   [6:0] trunc_ln177_fu_439_p1;
wire   [6:0] add_ln177_1_fu_461_p2;
wire   [6:0] tmp_4_fu_490_p3;
wire   [6:0] trunc_ln172_1_fu_486_p1;
wire   [6:0] add_ln172_fu_498_p2;
wire   [6:0] trunc_ln172_fu_482_p1;
wire   [6:0] add_ln172_1_fu_504_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_458;
reg    ap_condition_463;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

yusur_hash_allocation_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            b_fu_56 <= 4'd0;
        end else if (((icmp_ln140_fu_219_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            b_fu_56 <= add_ln148_fu_268_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd1) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)) | (~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd0) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)))) begin
        c_fu_76 <= grp_fu_181_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (val_fu_336_p1 == 8'd255) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (val_fu_336_p1 == 8'd254) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)))) begin
        c_fu_76 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_60 <= 31'd0;
        end else if (((icmp_ln140_fu_219_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_60 <= select_ln140_1_fu_256_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_64 <= 35'd0;
        end else if (((icmp_ln140_fu_219_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_64 <= add_ln140_fu_224_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1)) | (~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_159_p2 == 1'd1) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)))) begin
                m_idx_fu_72[0] <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (val_fu_336_p1 == 8'd255) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0))) begin
                m_idx_fu_72[0] <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (val_fu_336_p1 == 8'd255) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)))) begin
        r_fu_68 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (val_fu_336_p1 == 8'd254) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0))) begin
        r_fu_68 <= r_3_fu_408_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln140_reg_572 <= icmp_ln140_fu_219_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln140_reg_572_pp0_iter2_reg <= icmp_ln140_reg_572;
        icmp_ln140_reg_572_pp0_iter3_reg <= icmp_ln140_reg_572_pp0_iter2_reg;
        trunc_ln1669_reg_581_pp0_iter2_reg <= trunc_ln1669_reg_581;
        trunc_ln1669_reg_581_pp0_iter3_reg <= trunc_ln1669_reg_581_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln140_reg_572_pp0_iter2_reg == 1'd0))) begin
        batch_data_V_load_reg_597 <= batch_data_V_q0;
        r_V_reg_602 <= r_V_fu_303_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln140_fu_219_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln140_1_reg_576 <= select_ln140_1_fu_256_p3;
        trunc_ln1669_reg_581 <= trunc_ln1669_fu_264_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_458)) begin
        if ((~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254))) begin
            A_MATRIX_address0 = zext_ln172_fu_510_p1;
        end else if ((val_fu_336_p1 == 8'd254)) begin
            A_MATRIX_address0 = zext_ln162_fu_403_p1;
        end else begin
            A_MATRIX_address0 = 'bx;
        end
    end else begin
        A_MATRIX_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd1) & (val_fu_336_p1 == 8'd254) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)) | (~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd1) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)))) begin
        A_MATRIX_ce0 = 1'b1;
    end else begin
        A_MATRIX_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_458)) begin
        if ((~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254))) begin
            A_MATRIX_d0 = val_fu_336_p1;
        end else if ((val_fu_336_p1 == 8'd254)) begin
            A_MATRIX_d0 = 8'd254;
        end else begin
            A_MATRIX_d0 = 'bx;
        end
    end else begin
        A_MATRIX_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd1) & (val_fu_336_p1 == 8'd254) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)) | (~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd1) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)))) begin
        A_MATRIX_we0 = 1'b1;
    end else begin
        A_MATRIX_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_463)) begin
        if ((~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254))) begin
            B_MATRIX_address0 = zext_ln177_fu_467_p1;
        end else if ((val_fu_336_p1 == 8'd254)) begin
            B_MATRIX_address0 = zext_ln164_fu_370_p1;
        end else begin
            B_MATRIX_address0 = 'bx;
        end
    end else begin
        B_MATRIX_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd0) & (val_fu_336_p1 == 8'd254) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)) | (~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd0) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)))) begin
        B_MATRIX_ce0 = 1'b1;
    end else begin
        B_MATRIX_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_463)) begin
        if ((~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254))) begin
            B_MATRIX_d0 = val_fu_336_p1;
        end else if ((val_fu_336_p1 == 8'd254)) begin
            B_MATRIX_d0 = 8'd254;
        end else begin
            B_MATRIX_d0 = 'bx;
        end
    end else begin
        B_MATRIX_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd0) & (val_fu_336_p1 == 8'd254) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)) | (~(val_fu_336_p1 == 8'd255) & ~(val_fu_336_p1 == 8'd254) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd0) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0)))) begin
        B_MATRIX_we0 = 1'b1;
    end else begin
        B_MATRIX_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln140_fu_219_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        batch_data_V_ce0 = 1'b1;
    end else begin
        batch_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        keep_data_V_ce0 = 1'b1;
    end else begin
        keep_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln140_fu_224_p2 = (indvar_flatten_fu_64 + 35'd1);

assign add_ln145_fu_236_p2 = (i_fu_60 + 31'd1);

assign add_ln148_fu_268_p2 = (select_ln140_fu_248_p3 + 4'd1);

assign add_ln162_1_fu_397_p2 = (add_ln162_fu_391_p2 + trunc_ln162_fu_375_p1);

assign add_ln162_fu_391_p2 = (tmp_6_fu_383_p3 + trunc_ln162_1_fu_379_p1);

assign add_ln164_1_fu_364_p2 = (add_ln164_fu_358_p2 + trunc_ln164_fu_342_p1);

assign add_ln164_fu_358_p2 = (tmp_7_fu_350_p3 + trunc_ln164_1_fu_346_p1);

assign add_ln172_1_fu_504_p2 = (add_ln172_fu_498_p2 + trunc_ln172_fu_482_p1);

assign add_ln172_fu_498_p2 = (tmp_4_fu_490_p3 + trunc_ln172_1_fu_486_p1);

assign add_ln177_1_fu_461_p2 = (add_ln177_fu_455_p2 + trunc_ln177_fu_439_p1);

assign add_ln177_fu_455_p2 = (tmp_5_fu_447_p3 + trunc_ln177_1_fu_443_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_458 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd1) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_condition_463 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (grp_fu_175_p2 == 1'd1) & (grp_fu_159_p2 == 1'd0) & (r_V_reg_602 == 1'd1) & (icmp_ln140_reg_572_pp0_iter3_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign batch_data_V_address0 = zext_ln140_1_fu_289_p1;

assign grp_fu_159_p2 = ((m_idx_fu_72 == 32'd0) ? 1'b1 : 1'b0);

assign grp_fu_165_p2 = (($signed(r_fu_68) < $signed(32'd9)) ? 1'b1 : 1'b0);

assign grp_fu_170_p2 = (($signed(c_fu_76) < $signed(32'd9)) ? 1'b1 : 1'b0);

assign grp_fu_175_p2 = (grp_fu_170_p2 & grp_fu_165_p2);

assign grp_fu_181_p2 = (c_fu_76 + 32'd1);

assign icmp_ln140_fu_219_p2 = ((indvar_flatten_fu_64 == zext_ln140) ? 1'b1 : 1'b0);

assign icmp_ln148_fu_242_p2 = ((b_fu_56 == 4'd8) ? 1'b1 : 1'b0);

assign keep_data_V_address0 = zext_ln140_1_fu_289_p1;

assign lshr_ln1669_fu_297_p2 = keep_data_V_q0 >> zext_ln1669_fu_294_p1;

assign r_3_fu_408_p2 = (r_fu_68 + 32'd1);

assign r_V_1_fu_331_p2 = batch_data_V_load_reg_597 >> zext_ln1669_2_fu_327_p1;

assign r_V_fu_303_p1 = lshr_ln1669_fu_297_p2[0:0];

assign select_ln140_1_fu_256_p3 = ((icmp_ln148_fu_242_p2[0:0] == 1'b1) ? add_ln145_fu_236_p2 : i_fu_60);

assign select_ln140_fu_248_p3 = ((icmp_ln148_fu_242_p2[0:0] == 1'b1) ? 4'd0 : b_fu_56);

assign shl_ln_fu_320_p3 = {{trunc_ln1669_reg_581_pp0_iter3_reg}, {3'd0}};

assign tmp_4_fu_490_p3 = {{trunc_ln145_fu_316_p1}, {3'd0}};

assign tmp_5_fu_447_p3 = {{trunc_ln145_fu_316_p1}, {3'd0}};

assign tmp_6_fu_383_p3 = {{trunc_ln145_fu_316_p1}, {3'd0}};

assign tmp_7_fu_350_p3 = {{trunc_ln145_fu_316_p1}, {3'd0}};

assign trunc_ln145_fu_316_p1 = r_fu_68[3:0];

assign trunc_ln162_1_fu_379_p1 = r_fu_68[6:0];

assign trunc_ln162_fu_375_p1 = c_fu_76[6:0];

assign trunc_ln164_1_fu_346_p1 = r_fu_68[6:0];

assign trunc_ln164_fu_342_p1 = c_fu_76[6:0];

assign trunc_ln1669_fu_264_p1 = select_ln140_fu_248_p3[2:0];

assign trunc_ln172_1_fu_486_p1 = r_fu_68[6:0];

assign trunc_ln172_fu_482_p1 = c_fu_76[6:0];

assign trunc_ln177_1_fu_443_p1 = r_fu_68[6:0];

assign trunc_ln177_fu_439_p1 = c_fu_76[6:0];

assign val_fu_336_p1 = r_V_1_fu_331_p2[7:0];

assign zext_ln140_1_fu_289_p1 = select_ln140_1_reg_576;

assign zext_ln162_fu_403_p1 = add_ln162_1_fu_397_p2;

assign zext_ln164_fu_370_p1 = add_ln164_1_fu_364_p2;

assign zext_ln1669_2_fu_327_p1 = shl_ln_fu_320_p3;

assign zext_ln1669_fu_294_p1 = trunc_ln1669_reg_581_pp0_iter2_reg;

assign zext_ln172_fu_510_p1 = add_ln172_1_fu_504_p2;

assign zext_ln177_fu_467_p1 = add_ln177_1_fu_461_p2;

always @ (posedge ap_clk) begin
    m_idx_fu_72[31:1] <= 31'b0000000000000000000000000000000;
end

endmodule //yusur_hash_allocation_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4
