// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module yusur_hash_allocation_Block_entry19_proc3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        C_MATRIX_address0,
        C_MATRIX_ce0,
        C_MATRIX_we0,
        C_MATRIX_d0,
        C_MATRIX_address1,
        C_MATRIX_ce1,
        C_MATRIX_we1,
        C_MATRIX_d1,
        i_axiu_key_TDATA,
        i_axiu_key_TVALID,
        i_axiu_key_TREADY,
        i_axiu_stream_data_TDATA,
        i_axiu_stream_data_TVALID,
        i_axiu_stream_data_TREADY,
        i_axiu_stream_data_TKEEP,
        i_axiu_stream_data_TSTRB,
        i_axiu_stream_data_TLAST,
        i_axiu_user0_data_TDATA,
        i_axiu_user0_data_TVALID,
        i_axiu_user0_data_TREADY,
        i_axiu_user0_data_TKEEP,
        i_axiu_user0_data_TSTRB,
        i_axiu_user0_data_TLAST
);

parameter    ap_ST_fsm_state1 = 45'd1;
parameter    ap_ST_fsm_state2 = 45'd2;
parameter    ap_ST_fsm_state3 = 45'd4;
parameter    ap_ST_fsm_state4 = 45'd8;
parameter    ap_ST_fsm_state5 = 45'd16;
parameter    ap_ST_fsm_state6 = 45'd32;
parameter    ap_ST_fsm_state7 = 45'd64;
parameter    ap_ST_fsm_state8 = 45'd128;
parameter    ap_ST_fsm_state9 = 45'd256;
parameter    ap_ST_fsm_state10 = 45'd512;
parameter    ap_ST_fsm_state11 = 45'd1024;
parameter    ap_ST_fsm_state12 = 45'd2048;
parameter    ap_ST_fsm_state13 = 45'd4096;
parameter    ap_ST_fsm_state14 = 45'd8192;
parameter    ap_ST_fsm_state15 = 45'd16384;
parameter    ap_ST_fsm_state16 = 45'd32768;
parameter    ap_ST_fsm_state17 = 45'd65536;
parameter    ap_ST_fsm_state18 = 45'd131072;
parameter    ap_ST_fsm_state19 = 45'd262144;
parameter    ap_ST_fsm_state20 = 45'd524288;
parameter    ap_ST_fsm_state21 = 45'd1048576;
parameter    ap_ST_fsm_state22 = 45'd2097152;
parameter    ap_ST_fsm_state23 = 45'd4194304;
parameter    ap_ST_fsm_state24 = 45'd8388608;
parameter    ap_ST_fsm_state25 = 45'd16777216;
parameter    ap_ST_fsm_state26 = 45'd33554432;
parameter    ap_ST_fsm_state27 = 45'd67108864;
parameter    ap_ST_fsm_state28 = 45'd134217728;
parameter    ap_ST_fsm_state29 = 45'd268435456;
parameter    ap_ST_fsm_state30 = 45'd536870912;
parameter    ap_ST_fsm_state31 = 45'd1073741824;
parameter    ap_ST_fsm_state32 = 45'd2147483648;
parameter    ap_ST_fsm_state33 = 45'd4294967296;
parameter    ap_ST_fsm_state34 = 45'd8589934592;
parameter    ap_ST_fsm_state35 = 45'd17179869184;
parameter    ap_ST_fsm_state36 = 45'd34359738368;
parameter    ap_ST_fsm_state37 = 45'd68719476736;
parameter    ap_ST_fsm_state38 = 45'd137438953472;
parameter    ap_ST_fsm_state39 = 45'd274877906944;
parameter    ap_ST_fsm_state40 = 45'd549755813888;
parameter    ap_ST_fsm_state41 = 45'd1099511627776;
parameter    ap_ST_fsm_state42 = 45'd2199023255552;
parameter    ap_ST_fsm_state43 = 45'd4398046511104;
parameter    ap_ST_fsm_state44 = 45'd8796093022208;
parameter    ap_ST_fsm_state45 = 45'd17592186044416;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [6:0] C_MATRIX_address0;
output   C_MATRIX_ce0;
output   C_MATRIX_we0;
output  [7:0] C_MATRIX_d0;
output  [6:0] C_MATRIX_address1;
output   C_MATRIX_ce1;
output   C_MATRIX_we1;
output  [7:0] C_MATRIX_d1;
input  [79:0] i_axiu_key_TDATA;
input   i_axiu_key_TVALID;
output   i_axiu_key_TREADY;
input  [63:0] i_axiu_stream_data_TDATA;
input   i_axiu_stream_data_TVALID;
output   i_axiu_stream_data_TREADY;
input  [7:0] i_axiu_stream_data_TKEEP;
input  [7:0] i_axiu_stream_data_TSTRB;
input  [0:0] i_axiu_stream_data_TLAST;
input  [63:0] i_axiu_user0_data_TDATA;
input   i_axiu_user0_data_TVALID;
output   i_axiu_user0_data_TREADY;
input  [7:0] i_axiu_user0_data_TKEEP;
input  [7:0] i_axiu_user0_data_TSTRB;
input  [0:0] i_axiu_user0_data_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] C_MATRIX_address0;
reg C_MATRIX_ce0;
reg C_MATRIX_we0;
reg[7:0] C_MATRIX_d0;
reg[6:0] C_MATRIX_address1;
reg C_MATRIX_ce1;
reg C_MATRIX_we1;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [44:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    i_axiu_key_TDATA_blk_n;
wire   [34:0] tmp_fu_2351_p3;
reg   [34:0] tmp_reg_2366;
wire    ap_CS_fsm_state42;
reg   [6:0] A_MATRIX_address0;
reg    A_MATRIX_ce0;
reg    A_MATRIX_we0;
reg   [7:0] A_MATRIX_d0;
wire   [7:0] A_MATRIX_q0;
reg   [6:0] A_MATRIX_address1;
reg    A_MATRIX_ce1;
reg    A_MATRIX_we1;
reg   [6:0] B_MATRIX_address0;
reg    B_MATRIX_ce0;
reg    B_MATRIX_we0;
reg   [7:0] B_MATRIX_d0;
wire   [7:0] B_MATRIX_q0;
reg   [6:0] B_MATRIX_address1;
reg    B_MATRIX_ce1;
reg    B_MATRIX_we1;
reg   [7:0] batch_data_V_address0;
reg    batch_data_V_ce0;
reg    batch_data_V_we0;
wire   [63:0] batch_data_V_q0;
reg   [7:0] keep_data_V_address0;
reg    keep_data_V_ce0;
reg    keep_data_V_we0;
wire   [7:0] keep_data_V_q0;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_start;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_idle;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_ready;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_i_axiu_stream_data_TREADY;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_i_axiu_user0_data_TREADY;
wire   [7:0] grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_address0;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_ce0;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_we0;
wire   [63:0] grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_d0;
wire   [7:0] grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_address0;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_ce0;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_we0;
wire   [7:0] grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_d0;
wire   [31:0] grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_pkt_len_1_out;
wire    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_pkt_len_1_out_ap_vld;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_start;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_done;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_idle;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_ready;
wire   [7:0] grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_batch_data_V_address0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_batch_data_V_ce0;
wire   [7:0] grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_keep_data_V_address0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_keep_data_V_ce0;
wire   [6:0] grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_address0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_ce0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_we0;
wire   [7:0] grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_d0;
wire   [6:0] grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_address0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_ce0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_we0;
wire   [7:0] grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_d0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_start;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_done;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_idle;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_ready;
wire   [6:0] grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_address0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_ce0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_we0;
wire   [7:0] grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_d0;
wire   [6:0] grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_A_MATRIX_address0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_A_MATRIX_ce0;
wire   [6:0] grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_B_MATRIX_address0;
wire    grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_B_MATRIX_ce0;
reg    grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_start_reg;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state41;
reg    grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_start_reg;
wire    ap_CS_fsm_state43;
reg    grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_start_reg;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state45;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state39;
reg    ap_block_state1;
reg   [44:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
reg    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
reg    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
reg    ap_ST_fsm_state45_blk;
wire    regslice_both_i_axiu_key_U_apdone_blk;
wire   [79:0] i_axiu_key_TDATA_int_regslice;
wire    i_axiu_key_TVALID_int_regslice;
reg    i_axiu_key_TREADY_int_regslice;
wire    regslice_both_i_axiu_key_U_ack_in;
wire    regslice_both_i_axiu_stream_data_V_data_V_U_apdone_blk;
wire   [63:0] i_axiu_stream_data_TDATA_int_regslice;
wire    i_axiu_stream_data_TVALID_int_regslice;
reg    i_axiu_stream_data_TREADY_int_regslice;
wire    regslice_both_i_axiu_stream_data_V_data_V_U_ack_in;
wire    regslice_both_i_axiu_stream_data_V_keep_V_U_apdone_blk;
wire   [7:0] i_axiu_stream_data_TKEEP_int_regslice;
wire    regslice_both_i_axiu_stream_data_V_keep_V_U_vld_out;
wire    regslice_both_i_axiu_stream_data_V_keep_V_U_ack_in;
wire    regslice_both_i_axiu_stream_data_V_strb_V_U_apdone_blk;
wire   [7:0] i_axiu_stream_data_TSTRB_int_regslice;
wire    regslice_both_i_axiu_stream_data_V_strb_V_U_vld_out;
wire    regslice_both_i_axiu_stream_data_V_strb_V_U_ack_in;
wire    regslice_both_i_axiu_stream_data_V_last_V_U_apdone_blk;
wire   [0:0] i_axiu_stream_data_TLAST_int_regslice;
wire    regslice_both_i_axiu_stream_data_V_last_V_U_vld_out;
wire    regslice_both_i_axiu_stream_data_V_last_V_U_ack_in;
wire    regslice_both_i_axiu_user0_data_V_data_V_U_apdone_blk;
wire   [63:0] i_axiu_user0_data_TDATA_int_regslice;
wire    i_axiu_user0_data_TVALID_int_regslice;
reg    i_axiu_user0_data_TREADY_int_regslice;
wire    regslice_both_i_axiu_user0_data_V_data_V_U_ack_in;
wire    regslice_both_i_axiu_user0_data_V_keep_V_U_apdone_blk;
wire   [7:0] i_axiu_user0_data_TKEEP_int_regslice;
wire    regslice_both_i_axiu_user0_data_V_keep_V_U_vld_out;
wire    regslice_both_i_axiu_user0_data_V_keep_V_U_ack_in;
wire    regslice_both_i_axiu_user0_data_V_strb_V_U_apdone_blk;
wire   [7:0] i_axiu_user0_data_TSTRB_int_regslice;
wire    regslice_both_i_axiu_user0_data_V_strb_V_U_vld_out;
wire    regslice_both_i_axiu_user0_data_V_strb_V_U_ack_in;
wire    regslice_both_i_axiu_user0_data_V_last_V_U_apdone_blk;
wire   [0:0] i_axiu_user0_data_TLAST_int_regslice;
wire    regslice_both_i_axiu_user0_data_V_last_V_U_vld_out;
wire    regslice_both_i_axiu_user0_data_V_last_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 45'd1;
#0 grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_start_reg = 1'b0;
#0 grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_start_reg = 1'b0;
#0 grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_start_reg = 1'b0;
end

yusur_hash_allocation_Block_entry19_proc3_A_MATRIX_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 81 ),
    .AddressWidth( 7 ))
A_MATRIX_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(A_MATRIX_address0),
    .ce0(A_MATRIX_ce0),
    .we0(A_MATRIX_we0),
    .d0(A_MATRIX_d0),
    .q0(A_MATRIX_q0),
    .address1(A_MATRIX_address1),
    .ce1(A_MATRIX_ce1),
    .we1(A_MATRIX_we1),
    .d1(8'd0)
);

yusur_hash_allocation_Block_entry19_proc3_A_MATRIX_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 81 ),
    .AddressWidth( 7 ))
B_MATRIX_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B_MATRIX_address0),
    .ce0(B_MATRIX_ce0),
    .we0(B_MATRIX_we0),
    .d0(B_MATRIX_d0),
    .q0(B_MATRIX_q0),
    .address1(B_MATRIX_address1),
    .ce1(B_MATRIX_ce1),
    .we1(B_MATRIX_we1),
    .d1(8'd0)
);

yusur_hash_allocation_Block_entry19_proc3_batch_data_V_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
batch_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(batch_data_V_address0),
    .ce0(batch_data_V_ce0),
    .we0(batch_data_V_we0),
    .d0(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_d0),
    .q0(batch_data_V_q0)
);

yusur_hash_allocation_Block_entry19_proc3_keep_data_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
keep_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(keep_data_V_address0),
    .ce0(keep_data_V_ce0),
    .we0(keep_data_V_we0),
    .d0(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_d0),
    .q0(keep_data_V_q0)
);

yusur_hash_allocation_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3 grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_start),
    .ap_done(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done),
    .ap_idle(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_idle),
    .ap_ready(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_ready),
    .i_axiu_user0_data_TVALID(i_axiu_user0_data_TVALID_int_regslice),
    .i_axiu_stream_data_TDATA(i_axiu_stream_data_TDATA_int_regslice),
    .i_axiu_stream_data_TVALID(i_axiu_stream_data_TVALID_int_regslice),
    .i_axiu_stream_data_TREADY(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_i_axiu_stream_data_TREADY),
    .i_axiu_stream_data_TKEEP(i_axiu_stream_data_TKEEP_int_regslice),
    .i_axiu_stream_data_TSTRB(i_axiu_stream_data_TSTRB_int_regslice),
    .i_axiu_stream_data_TLAST(i_axiu_stream_data_TLAST_int_regslice),
    .i_axiu_user0_data_TDATA(i_axiu_user0_data_TDATA_int_regslice),
    .i_axiu_user0_data_TREADY(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_i_axiu_user0_data_TREADY),
    .i_axiu_user0_data_TKEEP(i_axiu_user0_data_TKEEP_int_regslice),
    .i_axiu_user0_data_TSTRB(i_axiu_user0_data_TSTRB_int_regslice),
    .i_axiu_user0_data_TLAST(i_axiu_user0_data_TLAST_int_regslice),
    .batch_data_V_address0(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_address0),
    .batch_data_V_ce0(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_ce0),
    .batch_data_V_we0(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_we0),
    .batch_data_V_d0(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_d0),
    .keep_data_V_address0(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_address0),
    .keep_data_V_ce0(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_ce0),
    .keep_data_V_we0(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_we0),
    .keep_data_V_d0(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_d0),
    .pkt_len_1_out(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_pkt_len_1_out),
    .pkt_len_1_out_ap_vld(grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_pkt_len_1_out_ap_vld)
);

yusur_hash_allocation_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4 grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_start),
    .ap_done(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_done),
    .ap_idle(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_idle),
    .ap_ready(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_ready),
    .zext_ln140(tmp_reg_2366),
    .batch_data_V_address0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_batch_data_V_address0),
    .batch_data_V_ce0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_batch_data_V_ce0),
    .batch_data_V_q0(batch_data_V_q0),
    .keep_data_V_address0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_keep_data_V_address0),
    .keep_data_V_ce0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_keep_data_V_ce0),
    .keep_data_V_q0(keep_data_V_q0),
    .A_MATRIX_address0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_address0),
    .A_MATRIX_ce0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_ce0),
    .A_MATRIX_we0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_we0),
    .A_MATRIX_d0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_d0),
    .B_MATRIX_address0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_address0),
    .B_MATRIX_ce0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_ce0),
    .B_MATRIX_we0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_we0),
    .B_MATRIX_d0(grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_d0)
);

yusur_hash_allocation_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5 grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_start),
    .ap_done(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_done),
    .ap_idle(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_idle),
    .ap_ready(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_ready),
    .C_MATRIX_address0(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_address0),
    .C_MATRIX_ce0(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_ce0),
    .C_MATRIX_we0(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_we0),
    .C_MATRIX_d0(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_d0),
    .A_MATRIX_address0(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_A_MATRIX_address0),
    .A_MATRIX_ce0(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_A_MATRIX_ce0),
    .A_MATRIX_q0(A_MATRIX_q0),
    .B_MATRIX_address0(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_B_MATRIX_address0),
    .B_MATRIX_ce0(grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_B_MATRIX_ce0),
    .B_MATRIX_q0(B_MATRIX_q0)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 80 ))
regslice_both_i_axiu_key_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_axiu_key_TDATA),
    .vld_in(i_axiu_key_TVALID),
    .ack_in(regslice_both_i_axiu_key_U_ack_in),
    .data_out(i_axiu_key_TDATA_int_regslice),
    .vld_out(i_axiu_key_TVALID_int_regslice),
    .ack_out(i_axiu_key_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_key_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 64 ))
regslice_both_i_axiu_stream_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_axiu_stream_data_TDATA),
    .vld_in(i_axiu_stream_data_TVALID),
    .ack_in(regslice_both_i_axiu_stream_data_V_data_V_U_ack_in),
    .data_out(i_axiu_stream_data_TDATA_int_regslice),
    .vld_out(i_axiu_stream_data_TVALID_int_regslice),
    .ack_out(i_axiu_stream_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_stream_data_V_data_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 8 ))
regslice_both_i_axiu_stream_data_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_axiu_stream_data_TKEEP),
    .vld_in(i_axiu_stream_data_TVALID),
    .ack_in(regslice_both_i_axiu_stream_data_V_keep_V_U_ack_in),
    .data_out(i_axiu_stream_data_TKEEP_int_regslice),
    .vld_out(regslice_both_i_axiu_stream_data_V_keep_V_U_vld_out),
    .ack_out(i_axiu_stream_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_stream_data_V_keep_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 8 ))
regslice_both_i_axiu_stream_data_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_axiu_stream_data_TSTRB),
    .vld_in(i_axiu_stream_data_TVALID),
    .ack_in(regslice_both_i_axiu_stream_data_V_strb_V_U_ack_in),
    .data_out(i_axiu_stream_data_TSTRB_int_regslice),
    .vld_out(regslice_both_i_axiu_stream_data_V_strb_V_U_vld_out),
    .ack_out(i_axiu_stream_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_stream_data_V_strb_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 1 ))
regslice_both_i_axiu_stream_data_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_axiu_stream_data_TLAST),
    .vld_in(i_axiu_stream_data_TVALID),
    .ack_in(regslice_both_i_axiu_stream_data_V_last_V_U_ack_in),
    .data_out(i_axiu_stream_data_TLAST_int_regslice),
    .vld_out(regslice_both_i_axiu_stream_data_V_last_V_U_vld_out),
    .ack_out(i_axiu_stream_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_stream_data_V_last_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 64 ))
regslice_both_i_axiu_user0_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_axiu_user0_data_TDATA),
    .vld_in(i_axiu_user0_data_TVALID),
    .ack_in(regslice_both_i_axiu_user0_data_V_data_V_U_ack_in),
    .data_out(i_axiu_user0_data_TDATA_int_regslice),
    .vld_out(i_axiu_user0_data_TVALID_int_regslice),
    .ack_out(i_axiu_user0_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_user0_data_V_data_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 8 ))
regslice_both_i_axiu_user0_data_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_axiu_user0_data_TKEEP),
    .vld_in(i_axiu_user0_data_TVALID),
    .ack_in(regslice_both_i_axiu_user0_data_V_keep_V_U_ack_in),
    .data_out(i_axiu_user0_data_TKEEP_int_regslice),
    .vld_out(regslice_both_i_axiu_user0_data_V_keep_V_U_vld_out),
    .ack_out(i_axiu_user0_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_user0_data_V_keep_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 8 ))
regslice_both_i_axiu_user0_data_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_axiu_user0_data_TSTRB),
    .vld_in(i_axiu_user0_data_TVALID),
    .ack_in(regslice_both_i_axiu_user0_data_V_strb_V_U_ack_in),
    .data_out(i_axiu_user0_data_TSTRB_int_regslice),
    .vld_out(regslice_both_i_axiu_user0_data_V_strb_V_U_vld_out),
    .ack_out(i_axiu_user0_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_user0_data_V_strb_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 1 ))
regslice_both_i_axiu_user0_data_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_axiu_user0_data_TLAST),
    .vld_in(i_axiu_user0_data_TVALID),
    .ack_in(regslice_both_i_axiu_user0_data_V_last_V_U_ack_in),
    .data_out(i_axiu_user0_data_TLAST_int_regslice),
    .vld_out(regslice_both_i_axiu_user0_data_V_last_V_U_vld_out),
    .ack_out(i_axiu_user0_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_user0_data_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state45))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state44)) begin
            grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_ready == 1'b1)) begin
            grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state42)) begin
            grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_ready == 1'b1)) begin
            grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state40)) begin
            grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_ready == 1'b1)) begin
            grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        tmp_reg_2366[34 : 3] <= tmp_fu_2351_p3[34 : 3];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        A_MATRIX_address0 = 64'd79;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        A_MATRIX_address0 = 64'd77;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        A_MATRIX_address0 = 64'd76;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        A_MATRIX_address0 = 64'd75;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        A_MATRIX_address0 = 64'd73;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        A_MATRIX_address0 = 64'd71;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        A_MATRIX_address0 = 64'd69;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        A_MATRIX_address0 = 64'd67;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        A_MATRIX_address0 = 64'd65;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        A_MATRIX_address0 = 64'd63;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        A_MATRIX_address0 = 64'd61;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        A_MATRIX_address0 = 64'd59;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        A_MATRIX_address0 = 64'd57;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A_MATRIX_address0 = 64'd55;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        A_MATRIX_address0 = 64'd53;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        A_MATRIX_address0 = 64'd51;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        A_MATRIX_address0 = 64'd49;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        A_MATRIX_address0 = 64'd47;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        A_MATRIX_address0 = 64'd45;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        A_MATRIX_address0 = 64'd43;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        A_MATRIX_address0 = 64'd41;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        A_MATRIX_address0 = 64'd39;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        A_MATRIX_address0 = 64'd37;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        A_MATRIX_address0 = 64'd35;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        A_MATRIX_address0 = 64'd33;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        A_MATRIX_address0 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        A_MATRIX_address0 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        A_MATRIX_address0 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        A_MATRIX_address0 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        A_MATRIX_address0 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_MATRIX_address0 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        A_MATRIX_address0 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_MATRIX_address0 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        A_MATRIX_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        A_MATRIX_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_MATRIX_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        A_MATRIX_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_MATRIX_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_MATRIX_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_MATRIX_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        A_MATRIX_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        A_MATRIX_address0 = grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_A_MATRIX_address0;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        A_MATRIX_address0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_address0;
    end else begin
        A_MATRIX_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        A_MATRIX_address1 = 64'd80;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        A_MATRIX_address1 = 64'd78;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        A_MATRIX_address1 = 64'd74;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        A_MATRIX_address1 = 64'd72;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        A_MATRIX_address1 = 64'd70;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        A_MATRIX_address1 = 64'd68;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        A_MATRIX_address1 = 64'd66;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        A_MATRIX_address1 = 64'd64;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        A_MATRIX_address1 = 64'd62;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        A_MATRIX_address1 = 64'd60;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        A_MATRIX_address1 = 64'd58;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        A_MATRIX_address1 = 64'd56;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A_MATRIX_address1 = 64'd54;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        A_MATRIX_address1 = 64'd52;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        A_MATRIX_address1 = 64'd50;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        A_MATRIX_address1 = 64'd48;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        A_MATRIX_address1 = 64'd46;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        A_MATRIX_address1 = 64'd44;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        A_MATRIX_address1 = 64'd42;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        A_MATRIX_address1 = 64'd40;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        A_MATRIX_address1 = 64'd38;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        A_MATRIX_address1 = 64'd36;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        A_MATRIX_address1 = 64'd34;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        A_MATRIX_address1 = 64'd32;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        A_MATRIX_address1 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        A_MATRIX_address1 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        A_MATRIX_address1 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        A_MATRIX_address1 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        A_MATRIX_address1 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_MATRIX_address1 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        A_MATRIX_address1 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_MATRIX_address1 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        A_MATRIX_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        A_MATRIX_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_MATRIX_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        A_MATRIX_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_MATRIX_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_MATRIX_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_MATRIX_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        A_MATRIX_address1 = 64'd0;
    end else begin
        A_MATRIX_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state40) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        A_MATRIX_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        A_MATRIX_ce0 = grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_A_MATRIX_ce0;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        A_MATRIX_ce0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_ce0;
    end else begin
        A_MATRIX_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state40) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        A_MATRIX_ce1 = 1'b1;
    end else begin
        A_MATRIX_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40))) begin
        A_MATRIX_d0 = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        A_MATRIX_d0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_d0;
    end else begin
        A_MATRIX_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state40) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        A_MATRIX_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        A_MATRIX_we0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_A_MATRIX_we0;
    end else begin
        A_MATRIX_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state40) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        A_MATRIX_we1 = 1'b1;
    end else begin
        A_MATRIX_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        B_MATRIX_address0 = 64'd79;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        B_MATRIX_address0 = 64'd77;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        B_MATRIX_address0 = 64'd76;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        B_MATRIX_address0 = 64'd75;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        B_MATRIX_address0 = 64'd73;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        B_MATRIX_address0 = 64'd71;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        B_MATRIX_address0 = 64'd69;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        B_MATRIX_address0 = 64'd67;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        B_MATRIX_address0 = 64'd65;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        B_MATRIX_address0 = 64'd63;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        B_MATRIX_address0 = 64'd61;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        B_MATRIX_address0 = 64'd59;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        B_MATRIX_address0 = 64'd57;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        B_MATRIX_address0 = 64'd55;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        B_MATRIX_address0 = 64'd53;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        B_MATRIX_address0 = 64'd51;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        B_MATRIX_address0 = 64'd49;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        B_MATRIX_address0 = 64'd47;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        B_MATRIX_address0 = 64'd45;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        B_MATRIX_address0 = 64'd43;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        B_MATRIX_address0 = 64'd41;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        B_MATRIX_address0 = 64'd39;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        B_MATRIX_address0 = 64'd37;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        B_MATRIX_address0 = 64'd35;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        B_MATRIX_address0 = 64'd33;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        B_MATRIX_address0 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        B_MATRIX_address0 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        B_MATRIX_address0 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_MATRIX_address0 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        B_MATRIX_address0 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        B_MATRIX_address0 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        B_MATRIX_address0 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        B_MATRIX_address0 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        B_MATRIX_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        B_MATRIX_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_MATRIX_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        B_MATRIX_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        B_MATRIX_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        B_MATRIX_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        B_MATRIX_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        B_MATRIX_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        B_MATRIX_address0 = grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_B_MATRIX_address0;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        B_MATRIX_address0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_address0;
    end else begin
        B_MATRIX_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        B_MATRIX_address1 = 64'd80;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        B_MATRIX_address1 = 64'd78;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        B_MATRIX_address1 = 64'd74;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        B_MATRIX_address1 = 64'd72;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        B_MATRIX_address1 = 64'd70;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        B_MATRIX_address1 = 64'd68;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        B_MATRIX_address1 = 64'd66;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        B_MATRIX_address1 = 64'd64;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        B_MATRIX_address1 = 64'd62;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        B_MATRIX_address1 = 64'd60;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        B_MATRIX_address1 = 64'd58;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        B_MATRIX_address1 = 64'd56;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        B_MATRIX_address1 = 64'd54;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        B_MATRIX_address1 = 64'd52;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        B_MATRIX_address1 = 64'd50;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        B_MATRIX_address1 = 64'd48;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        B_MATRIX_address1 = 64'd46;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        B_MATRIX_address1 = 64'd44;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        B_MATRIX_address1 = 64'd42;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        B_MATRIX_address1 = 64'd40;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        B_MATRIX_address1 = 64'd38;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        B_MATRIX_address1 = 64'd36;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        B_MATRIX_address1 = 64'd34;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        B_MATRIX_address1 = 64'd32;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        B_MATRIX_address1 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        B_MATRIX_address1 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        B_MATRIX_address1 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_MATRIX_address1 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        B_MATRIX_address1 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        B_MATRIX_address1 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        B_MATRIX_address1 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        B_MATRIX_address1 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        B_MATRIX_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        B_MATRIX_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_MATRIX_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        B_MATRIX_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        B_MATRIX_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        B_MATRIX_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        B_MATRIX_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        B_MATRIX_address1 = 64'd0;
    end else begin
        B_MATRIX_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state40) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        B_MATRIX_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        B_MATRIX_ce0 = grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_B_MATRIX_ce0;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        B_MATRIX_ce0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_ce0;
    end else begin
        B_MATRIX_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state40) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        B_MATRIX_ce1 = 1'b1;
    end else begin
        B_MATRIX_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40))) begin
        B_MATRIX_d0 = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        B_MATRIX_d0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_d0;
    end else begin
        B_MATRIX_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state40) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        B_MATRIX_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        B_MATRIX_we0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_B_MATRIX_we0;
    end else begin
        B_MATRIX_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state40) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        B_MATRIX_we1 = 1'b1;
    end else begin
        B_MATRIX_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        C_MATRIX_address0 = 64'd79;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        C_MATRIX_address0 = 64'd77;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        C_MATRIX_address0 = 64'd75;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        C_MATRIX_address0 = 64'd74;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        C_MATRIX_address0 = 64'd73;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        C_MATRIX_address0 = 64'd71;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        C_MATRIX_address0 = 64'd69;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        C_MATRIX_address0 = 64'd67;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        C_MATRIX_address0 = 64'd65;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        C_MATRIX_address0 = 64'd63;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        C_MATRIX_address0 = 64'd61;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        C_MATRIX_address0 = 64'd59;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        C_MATRIX_address0 = 64'd57;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        C_MATRIX_address0 = 64'd55;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        C_MATRIX_address0 = 64'd53;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        C_MATRIX_address0 = 64'd51;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        C_MATRIX_address0 = 64'd49;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        C_MATRIX_address0 = 64'd47;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        C_MATRIX_address0 = 64'd45;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        C_MATRIX_address0 = 64'd43;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        C_MATRIX_address0 = 64'd41;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        C_MATRIX_address0 = 64'd39;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        C_MATRIX_address0 = 64'd37;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        C_MATRIX_address0 = 64'd35;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        C_MATRIX_address0 = 64'd33;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        C_MATRIX_address0 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        C_MATRIX_address0 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        C_MATRIX_address0 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        C_MATRIX_address0 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        C_MATRIX_address0 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        C_MATRIX_address0 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        C_MATRIX_address0 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        C_MATRIX_address0 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_MATRIX_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        C_MATRIX_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        C_MATRIX_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_MATRIX_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        C_MATRIX_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        C_MATRIX_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_MATRIX_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        C_MATRIX_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        C_MATRIX_address0 = grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_address0;
    end else begin
        C_MATRIX_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        C_MATRIX_address1 = 64'd80;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        C_MATRIX_address1 = 64'd78;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        C_MATRIX_address1 = 64'd76;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        C_MATRIX_address1 = 64'd72;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        C_MATRIX_address1 = 64'd70;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        C_MATRIX_address1 = 64'd68;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        C_MATRIX_address1 = 64'd66;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        C_MATRIX_address1 = 64'd64;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        C_MATRIX_address1 = 64'd62;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        C_MATRIX_address1 = 64'd60;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        C_MATRIX_address1 = 64'd58;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        C_MATRIX_address1 = 64'd56;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        C_MATRIX_address1 = 64'd54;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        C_MATRIX_address1 = 64'd52;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        C_MATRIX_address1 = 64'd50;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        C_MATRIX_address1 = 64'd48;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        C_MATRIX_address1 = 64'd46;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        C_MATRIX_address1 = 64'd44;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        C_MATRIX_address1 = 64'd42;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        C_MATRIX_address1 = 64'd40;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        C_MATRIX_address1 = 64'd38;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        C_MATRIX_address1 = 64'd36;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        C_MATRIX_address1 = 64'd34;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        C_MATRIX_address1 = 64'd32;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        C_MATRIX_address1 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        C_MATRIX_address1 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        C_MATRIX_address1 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        C_MATRIX_address1 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        C_MATRIX_address1 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        C_MATRIX_address1 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        C_MATRIX_address1 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        C_MATRIX_address1 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_MATRIX_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        C_MATRIX_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        C_MATRIX_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_MATRIX_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        C_MATRIX_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        C_MATRIX_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_MATRIX_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        C_MATRIX_address1 = 64'd0;
    end else begin
        C_MATRIX_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state42) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state43) & (grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        C_MATRIX_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        C_MATRIX_ce0 = grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_ce0;
    end else begin
        C_MATRIX_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state42) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state43) & (grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        C_MATRIX_ce1 = 1'b1;
    end else begin
        C_MATRIX_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state42))) begin
        C_MATRIX_d0 = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        C_MATRIX_d0 = grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_d0;
    end else begin
        C_MATRIX_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state42) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state43) & (grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        C_MATRIX_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        C_MATRIX_we0 = grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_C_MATRIX_we0;
    end else begin
        C_MATRIX_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state42) | (~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state43) & (grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1)))) begin
        C_MATRIX_we1 = 1'b1;
    end else begin
        C_MATRIX_we1 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

always @ (*) begin
    if ((grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b0)) begin
        ap_ST_fsm_state41_blk = 1'b1;
    end else begin
        ap_ST_fsm_state41_blk = 1'b0;
    end
end

assign ap_ST_fsm_state42_blk = 1'b0;

always @ (*) begin
    if ((grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_done == 1'b0)) begin
        ap_ST_fsm_state43_blk = 1'b1;
    end else begin
        ap_ST_fsm_state43_blk = 1'b0;
    end
end

assign ap_ST_fsm_state44_blk = 1'b0;

always @ (*) begin
    if ((grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_done == 1'b0)) begin
        ap_ST_fsm_state45_blk = 1'b1;
    end else begin
        ap_ST_fsm_state45_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        batch_data_V_address0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_batch_data_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        batch_data_V_address0 = grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_address0;
    end else begin
        batch_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        batch_data_V_ce0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_batch_data_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        batch_data_V_ce0 = grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_ce0;
    end else begin
        batch_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        batch_data_V_we0 = grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_batch_data_V_we0;
    end else begin
        batch_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_axiu_key_TDATA_blk_n = i_axiu_key_TVALID_int_regslice;
    end else begin
        i_axiu_key_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_axiu_key_TREADY_int_regslice = 1'b1;
    end else begin
        i_axiu_key_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        i_axiu_stream_data_TREADY_int_regslice = grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_i_axiu_stream_data_TREADY;
    end else begin
        i_axiu_stream_data_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        i_axiu_user0_data_TREADY_int_regslice = grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_i_axiu_user0_data_TREADY;
    end else begin
        i_axiu_user0_data_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        keep_data_V_address0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_keep_data_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        keep_data_V_address0 = grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_address0;
    end else begin
        keep_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        keep_data_V_ce0 = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_keep_data_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        keep_data_V_ce0 = grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_ce0;
    end else begin
        keep_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        keep_data_V_we0 = grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_keep_data_V_we0;
    end else begin
        keep_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            if (((1'b1 == ap_CS_fsm_state41) & (grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            if (((1'b1 == ap_CS_fsm_state43) & (grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            if (((grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state45))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_MATRIX_d1 = 8'd0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((i_axiu_key_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_start = grp_Block_entry19_proc3_Pipeline_LOOP_CALC_VITIS_LOOP_188_5_fu_2340_ap_start_reg;

assign grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_start = grp_Block_entry19_proc3_Pipeline_LOOP_MATRIX_PROCESS_VITIS_LOOP_148_4_fu_2331_ap_start_reg;

assign grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_start = grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_ap_start_reg;

assign i_axiu_key_TREADY = regslice_both_i_axiu_key_U_ack_in;

assign i_axiu_stream_data_TREADY = regslice_both_i_axiu_stream_data_V_data_V_U_ack_in;

assign i_axiu_user0_data_TREADY = regslice_both_i_axiu_user0_data_V_data_V_U_ack_in;

assign tmp_fu_2351_p3 = {{grp_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3_fu_2308_pkt_len_1_out}, {3'd0}};

always @ (posedge ap_clk) begin
    tmp_reg_2366[2:0] <= 3'b000;
end

endmodule //yusur_hash_allocation_Block_entry19_proc3
