// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module yusur_hash_allocation_Loop_LOOP_FORWARD_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        o_axiu_user0_data_TREADY,
        p_read,
        batch_data_out_V_address0,
        batch_data_out_V_ce0,
        batch_data_out_V_q0,
        keep_data_out_V_address0,
        keep_data_out_V_ce0,
        keep_data_out_V_q0,
        last_data_out_V_address0,
        last_data_out_V_ce0,
        last_data_out_V_q0,
        o_axiu_user0_data_TDATA,
        o_axiu_user0_data_TVALID,
        o_axiu_user0_data_TKEEP,
        o_axiu_user0_data_TSTRB,
        o_axiu_user0_data_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   o_axiu_user0_data_TREADY;
input  [31:0] p_read;
output  [7:0] batch_data_out_V_address0;
output   batch_data_out_V_ce0;
input  [63:0] batch_data_out_V_q0;
output  [7:0] keep_data_out_V_address0;
output   keep_data_out_V_ce0;
input  [7:0] keep_data_out_V_q0;
output  [7:0] last_data_out_V_address0;
output   last_data_out_V_ce0;
input  [0:0] last_data_out_V_q0;
output  [63:0] o_axiu_user0_data_TDATA;
output   o_axiu_user0_data_TVALID;
output  [7:0] o_axiu_user0_data_TKEEP;
output  [7:0] o_axiu_user0_data_TSTRB;
output  [0:0] o_axiu_user0_data_TLAST;

reg ap_idle;
reg batch_data_out_V_ce0;
reg keep_data_out_V_ce0;
reg last_data_out_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln241_fu_137_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    o_axiu_user0_data_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] i_3_cast4_i_fu_149_p1;
reg   [30:0] i_fu_56;
wire   [30:0] add_ln241_fu_143_p2;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_i_2;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] i_3_cast_i_fu_133_p1;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    o_axiu_user0_data_TVALID_int_regslice;
wire    o_axiu_user0_data_TREADY_int_regslice;
wire    regslice_both_o_axiu_user0_data_V_data_V_U_vld_out;
wire    regslice_both_o_axiu_user0_data_V_keep_V_U_apdone_blk;
wire    regslice_both_o_axiu_user0_data_V_keep_V_U_ack_in_dummy;
wire    regslice_both_o_axiu_user0_data_V_keep_V_U_vld_out;
wire    regslice_both_o_axiu_user0_data_V_strb_V_U_apdone_blk;
wire    regslice_both_o_axiu_user0_data_V_strb_V_U_ack_in_dummy;
wire    regslice_both_o_axiu_user0_data_V_strb_V_U_vld_out;
wire    regslice_both_o_axiu_user0_data_V_last_V_U_apdone_blk;
wire    regslice_both_o_axiu_user0_data_V_last_V_U_ack_in_dummy;
wire    regslice_both_o_axiu_user0_data_V_last_V_U_vld_out;
reg    ap_condition_130;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

yusur_hash_allocation_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 64 ))
regslice_both_o_axiu_user0_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(batch_data_out_V_q0),
    .vld_in(o_axiu_user0_data_TVALID_int_regslice),
    .ack_in(o_axiu_user0_data_TREADY_int_regslice),
    .data_out(o_axiu_user0_data_TDATA),
    .vld_out(regslice_both_o_axiu_user0_data_V_data_V_U_vld_out),
    .ack_out(o_axiu_user0_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 8 ))
regslice_both_o_axiu_user0_data_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(keep_data_out_V_q0),
    .vld_in(o_axiu_user0_data_TVALID_int_regslice),
    .ack_in(regslice_both_o_axiu_user0_data_V_keep_V_U_ack_in_dummy),
    .data_out(o_axiu_user0_data_TKEEP),
    .vld_out(regslice_both_o_axiu_user0_data_V_keep_V_U_vld_out),
    .ack_out(o_axiu_user0_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_user0_data_V_keep_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 8 ))
regslice_both_o_axiu_user0_data_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(8'd0),
    .vld_in(o_axiu_user0_data_TVALID_int_regslice),
    .ack_in(regslice_both_o_axiu_user0_data_V_strb_V_U_ack_in_dummy),
    .data_out(o_axiu_user0_data_TSTRB),
    .vld_out(regslice_both_o_axiu_user0_data_V_strb_V_U_vld_out),
    .ack_out(o_axiu_user0_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_user0_data_V_strb_V_U_apdone_blk)
);

yusur_hash_allocation_regslice_both #(
    .DataWidth( 1 ))
regslice_both_o_axiu_user0_data_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(last_data_out_V_q0),
    .vld_in(o_axiu_user0_data_TVALID_int_regslice),
    .ack_in(regslice_both_o_axiu_user0_data_V_last_V_U_ack_in_dummy),
    .data_out(o_axiu_user0_data_TLAST),
    .vld_out(regslice_both_o_axiu_user0_data_V_last_V_U_vld_out),
    .ack_out(o_axiu_user0_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_user0_data_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_130)) begin
        if ((icmp_ln241_fu_137_p2 == 1'd1)) begin
            i_fu_56 <= add_ln241_fu_143_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_56 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (*) begin
    if (((icmp_ln241_fu_137_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 31'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        batch_data_out_V_ce0 = 1'b1;
    end else begin
        batch_data_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        keep_data_out_V_ce0 = 1'b1;
    end else begin
        keep_data_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        last_data_out_V_ce0 = 1'b1;
    end else begin
        last_data_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        o_axiu_user0_data_TDATA_blk_n = o_axiu_user0_data_TREADY_int_regslice;
    end else begin
        o_axiu_user0_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        o_axiu_user0_data_TVALID_int_regslice = 1'b1;
    end else begin
        o_axiu_user0_data_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln241_fu_143_p2 = (ap_sig_allocacmp_i_2 + 31'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (o_axiu_user0_data_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1) | (o_axiu_user0_data_TREADY_int_regslice == 1'b0))) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (o_axiu_user0_data_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1) | (o_axiu_user0_data_TREADY_int_regslice == 1'b0))) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (o_axiu_user0_data_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1) | (o_axiu_user0_data_TREADY_int_regslice == 1'b0))) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((regslice_both_o_axiu_user0_data_V_data_V_U_apdone_blk == 1'b1) | (o_axiu_user0_data_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (o_axiu_user0_data_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_condition_130 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign batch_data_out_V_address0 = i_3_cast4_i_fu_149_p1;

assign i_3_cast4_i_fu_149_p1 = ap_sig_allocacmp_i_2;

assign i_3_cast_i_fu_133_p1 = ap_sig_allocacmp_i_2;

assign icmp_ln241_fu_137_p2 = (($signed(i_3_cast_i_fu_133_p1) < $signed(p_read)) ? 1'b1 : 1'b0);

assign keep_data_out_V_address0 = i_3_cast4_i_fu_149_p1;

assign last_data_out_V_address0 = i_3_cast4_i_fu_149_p1;

assign o_axiu_user0_data_TVALID = regslice_both_o_axiu_user0_data_V_data_V_U_vld_out;

endmodule //yusur_hash_allocation_Loop_LOOP_FORWARD_proc
