// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module yusur_hash_allocation_Loop_LOOP_PACK_OUTPUT_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        C_MATRIX_address0,
        C_MATRIX_ce0,
        C_MATRIX_q0,
        batch_data_out_V_address0,
        batch_data_out_V_ce0,
        batch_data_out_V_we0,
        batch_data_out_V_d0,
        keep_data_out_V_address0,
        keep_data_out_V_ce0,
        keep_data_out_V_we0,
        keep_data_out_V_d0,
        last_data_out_V_address0,
        last_data_out_V_ce0,
        last_data_out_V_we0,
        last_data_out_V_d0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [6:0] C_MATRIX_address0;
output   C_MATRIX_ce0;
input  [7:0] C_MATRIX_q0;
output  [7:0] batch_data_out_V_address0;
output   batch_data_out_V_ce0;
output   batch_data_out_V_we0;
output  [63:0] batch_data_out_V_d0;
output  [7:0] keep_data_out_V_address0;
output   keep_data_out_V_ce0;
output   keep_data_out_V_we0;
output  [7:0] keep_data_out_V_d0;
output  [7:0] last_data_out_V_address0;
output   last_data_out_V_ce0;
output   last_data_out_V_we0;
output  [0:0] last_data_out_V_d0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg C_MATRIX_ce0;
reg[7:0] batch_data_out_V_address0;
reg batch_data_out_V_ce0;
reg batch_data_out_V_we0;
reg[63:0] batch_data_out_V_d0;
reg[7:0] keep_data_out_V_address0;
reg keep_data_out_V_ce0;
reg keep_data_out_V_we0;
reg[7:0] keep_data_out_V_d0;
reg[7:0] last_data_out_V_address0;
reg last_data_out_V_ce0;
reg last_data_out_V_we0;
reg[0:0] last_data_out_V_d0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] pkt_len_out_2_reg_467;
wire    ap_CS_fsm_state2;
wire   [6:0] add_ln206_fu_222_p2;
reg   [6:0] add_ln206_reg_474;
wire   [3:0] add_ln203_fu_234_p2;
reg   [3:0] add_ln203_reg_482;
wire   [7:0] add_ln214_fu_277_p2;
reg   [7:0] add_ln214_reg_493;
wire   [0:0] icmp_ln203_fu_228_p2;
wire   [0:0] icmp_ln229_fu_244_p2;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln204_fu_297_p2;
reg   [0:0] icmp_ln204_reg_503;
wire   [3:0] add_ln204_fu_303_p2;
reg   [3:0] add_ln204_reg_507;
wire   [63:0] temp_word_V_1_fu_367_p2;
reg   [63:0] temp_word_V_1_reg_515;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln208_fu_309_p2;
wire   [0:0] icmp_ln217_fu_379_p2;
reg   [0:0] icmp_ln217_reg_521;
wire   [31:0] pkt_len_out_5_fu_432_p2;
wire    ap_CS_fsm_state6;
reg   [3:0] j_reg_157;
wire    ap_CS_fsm_state5;
reg   [31:0] pkt_len_out_3_reg_168;
wire   [63:0] zext_ln236_fu_262_p1;
wire   [0:0] icmp_ln234_fu_250_p2;
wire   [63:0] zext_ln206_2_fu_292_p1;
wire   [63:0] zext_ln218_fu_398_p1;
wire   [63:0] zext_ln230_fu_426_p1;
reg   [3:0] i_fu_54;
reg    ap_block_state1;
reg   [31:0] pkt_len_out_fu_58;
wire   [31:0] pkt_len_out_6_fu_405_p2;
reg   [31:0] byte_idx_fu_62;
wire   [31:0] byte_idx_1_fu_373_p2;
reg   [63:0] temp_word_V_fu_66;
wire   [6:0] tmp_fu_214_p3;
wire   [6:0] zext_ln206_fu_210_p1;
wire   [7:0] trunc_ln199_fu_240_p1;
wire   [7:0] add_ln236_fu_256_p2;
wire   [31:0] shl_ln231_fu_267_p2;
wire   [7:0] trunc_ln231_fu_273_p1;
wire   [6:0] zext_ln206_1_fu_283_p1;
wire   [6:0] add_ln206_1_fu_287_p2;
wire   [31:0] shl_ln214_fu_319_p2;
wire   [63:0] zext_ln211_fu_315_p1;
wire   [63:0] zext_ln1669_fu_333_p1;
wire   [31:0] sub_ln1669_fu_343_p2;
wire   [63:0] zext_ln1669_1_fu_349_p1;
wire   [0:0] tmp_1_fu_325_p3;
wire   [63:0] lshr_ln1669_fu_353_p2;
wire   [63:0] shl_ln1669_fu_337_p2;
wire   [63:0] r_V_fu_359_p3;
wire    ap_CS_fsm_state7;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln208_fu_309_p2 == 1'd0) & (icmp_ln204_reg_503 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln217_fu_379_p2 == 1'd0))) begin
        byte_idx_fu_62 <= byte_idx_1_fu_373_p2;
    end else if (((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln217_reg_521 == 1'd1)))) begin
        byte_idx_fu_62 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_54 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln208_fu_309_p2 == 1'd1) | (icmp_ln204_reg_503 == 1'd1)))) begin
        i_fu_54 <= add_ln203_reg_482;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_reg_157 <= add_ln204_reg_507;
    end else if (((icmp_ln203_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_157 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln229_fu_244_p2 == 1'd0) & (icmp_ln203_fu_228_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        pkt_len_out_3_reg_168 <= pkt_len_out_fu_58;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        pkt_len_out_3_reg_168 <= pkt_len_out_5_fu_432_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        pkt_len_out_fu_58 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln217_reg_521 == 1'd1))) begin
        pkt_len_out_fu_58 <= pkt_len_out_6_fu_405_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln217_reg_521 == 1'd1)))) begin
        temp_word_V_fu_66 <= 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln217_reg_521 == 1'd0))) begin
        temp_word_V_fu_66 <= temp_word_V_1_reg_515;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln203_reg_482 <= add_ln203_fu_234_p2;
        add_ln206_reg_474 <= add_ln206_fu_222_p2;
        pkt_len_out_2_reg_467 <= pkt_len_out_fu_58;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln204_reg_507 <= add_ln204_fu_303_p2;
        icmp_ln204_reg_503 <= icmp_ln204_fu_297_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln229_fu_244_p2 == 1'd1) & (icmp_ln203_fu_228_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln214_reg_493 <= add_ln214_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln208_fu_309_p2 == 1'd0) & (icmp_ln204_reg_503 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        icmp_ln217_reg_521 <= icmp_ln217_fu_379_p2;
        temp_word_V_1_reg_515 <= temp_word_V_1_fu_367_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        C_MATRIX_ce0 = 1'b1;
    end else begin
        C_MATRIX_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        batch_data_out_V_address0 = zext_ln230_fu_426_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        batch_data_out_V_address0 = zext_ln218_fu_398_p1;
    end else begin
        batch_data_out_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6))) begin
        batch_data_out_V_ce0 = 1'b1;
    end else begin
        batch_data_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        batch_data_out_V_d0 = temp_word_V_fu_66;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        batch_data_out_V_d0 = temp_word_V_1_reg_515;
    end else begin
        batch_data_out_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln217_reg_521 == 1'd1)))) begin
        batch_data_out_V_we0 = 1'b1;
    end else begin
        batch_data_out_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        keep_data_out_V_address0 = zext_ln230_fu_426_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        keep_data_out_V_address0 = zext_ln218_fu_398_p1;
    end else begin
        keep_data_out_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6))) begin
        keep_data_out_V_ce0 = 1'b1;
    end else begin
        keep_data_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        keep_data_out_V_d0 = add_ln214_reg_493;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        keep_data_out_V_d0 = 8'd255;
    end else begin
        keep_data_out_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln217_reg_521 == 1'd1)))) begin
        keep_data_out_V_we0 = 1'b1;
    end else begin
        keep_data_out_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        last_data_out_V_address0 = zext_ln230_fu_426_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        last_data_out_V_address0 = zext_ln218_fu_398_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        last_data_out_V_address0 = zext_ln236_fu_262_p1;
    end else begin
        last_data_out_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6))) begin
        last_data_out_V_ce0 = 1'b1;
    end else begin
        last_data_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        last_data_out_V_d0 = 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state6))) begin
        last_data_out_V_d0 = 1'd1;
    end else begin
        last_data_out_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((icmp_ln229_fu_244_p2 == 1'd0) & (icmp_ln203_fu_228_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln234_fu_250_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln217_reg_521 == 1'd1)))) begin
        last_data_out_V_we0 = 1'b1;
    end else begin
        last_data_out_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln229_fu_244_p2 == 1'd0) & (icmp_ln203_fu_228_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((icmp_ln229_fu_244_p2 == 1'd1) & (icmp_ln203_fu_228_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln208_fu_309_p2 == 1'd1) | (icmp_ln204_reg_503 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_MATRIX_address0 = zext_ln206_2_fu_292_p1;

assign add_ln203_fu_234_p2 = (i_fu_54 + 4'd1);

assign add_ln204_fu_303_p2 = (j_reg_157 + 4'd1);

assign add_ln206_1_fu_287_p2 = (add_ln206_reg_474 + zext_ln206_1_fu_283_p1);

assign add_ln206_fu_222_p2 = (tmp_fu_214_p3 + zext_ln206_fu_210_p1);

assign add_ln214_fu_277_p2 = ($signed(trunc_ln231_fu_273_p1) + $signed(8'd255));

assign add_ln236_fu_256_p2 = ($signed(trunc_ln199_fu_240_p1) + $signed(8'd255));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_return = pkt_len_out_3_reg_168;

assign byte_idx_1_fu_373_p2 = (byte_idx_fu_62 + 32'd1);

assign icmp_ln203_fu_228_p2 = ((i_fu_54 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln204_fu_297_p2 = ((j_reg_157 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln208_fu_309_p2 = ((C_MATRIX_q0 > 8'd253) ? 1'b1 : 1'b0);

assign icmp_ln217_fu_379_p2 = ((byte_idx_1_fu_373_p2 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln229_fu_244_p2 = (($signed(byte_idx_fu_62) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln234_fu_250_p2 = (($signed(pkt_len_out_fu_58) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign lshr_ln1669_fu_353_p2 = zext_ln211_fu_315_p1 >> zext_ln1669_1_fu_349_p1;

assign pkt_len_out_5_fu_432_p2 = (pkt_len_out_2_reg_467 + 32'd1);

assign pkt_len_out_6_fu_405_p2 = (pkt_len_out_fu_58 + 32'd1);

assign r_V_fu_359_p3 = ((tmp_1_fu_325_p3[0:0] == 1'b1) ? lshr_ln1669_fu_353_p2 : shl_ln1669_fu_337_p2);

assign shl_ln1669_fu_337_p2 = zext_ln211_fu_315_p1 << zext_ln1669_fu_333_p1;

assign shl_ln214_fu_319_p2 = byte_idx_fu_62 << 32'd3;

assign shl_ln231_fu_267_p2 = 32'd1 << byte_idx_fu_62;

assign sub_ln1669_fu_343_p2 = (32'd0 - shl_ln214_fu_319_p2);

assign temp_word_V_1_fu_367_p2 = (temp_word_V_fu_66 | r_V_fu_359_p3);

assign tmp_1_fu_325_p3 = byte_idx_fu_62[32'd28];

assign tmp_fu_214_p3 = {{i_fu_54}, {3'd0}};

assign trunc_ln199_fu_240_p1 = pkt_len_out_fu_58[7:0];

assign trunc_ln231_fu_273_p1 = shl_ln231_fu_267_p2[7:0];

assign zext_ln1669_1_fu_349_p1 = sub_ln1669_fu_343_p2;

assign zext_ln1669_fu_333_p1 = shl_ln214_fu_319_p2;

assign zext_ln206_1_fu_283_p1 = j_reg_157;

assign zext_ln206_2_fu_292_p1 = add_ln206_1_fu_287_p2;

assign zext_ln206_fu_210_p1 = i_fu_54;

assign zext_ln211_fu_315_p1 = C_MATRIX_q0;

assign zext_ln218_fu_398_p1 = pkt_len_out_fu_58;

assign zext_ln230_fu_426_p1 = pkt_len_out_2_reg_467;

assign zext_ln236_fu_262_p1 = add_ln236_fu_256_p2;

endmodule //yusur_hash_allocation_Loop_LOOP_PACK_OUTPUT_proc
