// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module yusur_hash_allocation_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i_axiu_user0_data_TVALID,
        i_axiu_stream_data_TDATA,
        i_axiu_stream_data_TVALID,
        i_axiu_stream_data_TREADY,
        i_axiu_stream_data_TKEEP,
        i_axiu_stream_data_TSTRB,
        i_axiu_stream_data_TLAST,
        i_axiu_user0_data_TDATA,
        i_axiu_user0_data_TREADY,
        i_axiu_user0_data_TKEEP,
        i_axiu_user0_data_TSTRB,
        i_axiu_user0_data_TLAST,
        batch_data_V_address0,
        batch_data_V_ce0,
        batch_data_V_we0,
        batch_data_V_d0,
        keep_data_V_address0,
        keep_data_V_ce0,
        keep_data_V_we0,
        keep_data_V_d0,
        pkt_len_1_out,
        pkt_len_1_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   i_axiu_user0_data_TVALID;
input  [63:0] i_axiu_stream_data_TDATA;
input   i_axiu_stream_data_TVALID;
output   i_axiu_stream_data_TREADY;
input  [7:0] i_axiu_stream_data_TKEEP;
input  [7:0] i_axiu_stream_data_TSTRB;
input  [0:0] i_axiu_stream_data_TLAST;
input  [63:0] i_axiu_user0_data_TDATA;
output   i_axiu_user0_data_TREADY;
input  [7:0] i_axiu_user0_data_TKEEP;
input  [7:0] i_axiu_user0_data_TSTRB;
input  [0:0] i_axiu_user0_data_TLAST;
output  [7:0] batch_data_V_address0;
output   batch_data_V_ce0;
output   batch_data_V_we0;
output  [63:0] batch_data_V_d0;
output  [7:0] keep_data_V_address0;
output   keep_data_V_ce0;
output   keep_data_V_we0;
output  [7:0] keep_data_V_d0;
output  [31:0] pkt_len_1_out;
output   pkt_len_1_out_ap_vld;

reg ap_idle;
reg i_axiu_stream_data_TREADY;
reg i_axiu_user0_data_TREADY;
reg batch_data_V_ce0;
reg batch_data_V_we0;
reg keep_data_V_ce0;
reg keep_data_V_we0;
reg pkt_len_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] tmp_last_V_fu_147_p1;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    i_axiu_user0_data_TDATA_blk_n;
wire   [63:0] zext_ln132_fu_167_p1;
wire   [0:0] icmp_ln131_fu_161_p2;
reg   [31:0] pkt_len_fu_68;
wire   [31:0] pkt_len_2_fu_173_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_pkt_len_1;
wire   [23:0] tmp_fu_151_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_152;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

yusur_hash_allocation_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_152)) begin
        if ((icmp_ln131_fu_161_p2 == 1'd1)) begin
            pkt_len_fu_68 <= pkt_len_2_fu_173_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            pkt_len_fu_68 <= 32'd0;
        end
    end
end

always @ (*) begin
    if (((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (tmp_last_V_fu_147_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_pkt_len_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_pkt_len_1 = pkt_len_fu_68;
    end
end

always @ (*) begin
    if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        batch_data_V_ce0 = 1'b1;
    end else begin
        batch_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (icmp_ln131_fu_161_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        batch_data_V_we0 = 1'b1;
    end else begin
        batch_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (i_axiu_stream_data_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_axiu_stream_data_TREADY = 1'b1;
    end else begin
        i_axiu_stream_data_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        i_axiu_user0_data_TDATA_blk_n = i_axiu_user0_data_TVALID;
    end else begin
        i_axiu_user0_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_axiu_user0_data_TREADY = 1'b1;
    end else begin
        i_axiu_user0_data_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        keep_data_V_ce0 = 1'b1;
    end else begin
        keep_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (icmp_ln131_fu_161_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        keep_data_V_we0 = 1'b1;
    end else begin
        keep_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (tmp_last_V_fu_147_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        pkt_len_1_out_ap_vld = 1'b1;
    end else begin
        pkt_len_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0));
end

always @ (*) begin
    ap_condition_152 = (~((i_axiu_user0_data_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign batch_data_V_address0 = zext_ln132_fu_167_p1;

assign batch_data_V_d0 = i_axiu_user0_data_TDATA;

assign icmp_ln131_fu_161_p2 = (($signed(tmp_fu_151_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign keep_data_V_address0 = zext_ln132_fu_167_p1;

assign keep_data_V_d0 = i_axiu_user0_data_TKEEP;

assign pkt_len_1_out = pkt_len_fu_68;

assign pkt_len_2_fu_173_p2 = (ap_sig_allocacmp_pkt_len_1 + 32'd1);

assign tmp_fu_151_p4 = {{ap_sig_allocacmp_pkt_len_1[31:8]}};

assign tmp_last_V_fu_147_p1 = i_axiu_user0_data_TLAST;

assign zext_ln132_fu_167_p1 = ap_sig_allocacmp_pkt_len_1;

endmodule //yusur_hash_allocation_Block_entry19_proc3_Pipeline_VITIS_LOOP_127_3
