# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.runs/synth_1/yusur_ndpp_x1100.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku15p_CIV-ffve1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.cache/wt [current_project]
set_property parent.project_path /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files -quiet /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/ip/yusur_ndpp_fdk/yusur_ndpp_x1100.dcp
set_property used_in_implementation false [get_files /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/ip/yusur_ndpp_fdk/yusur_ndpp_x1100.dcp]
read_verilog /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/yusur_ndpp_fpga_header.vh
set_property is_global_include true [get_files /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/yusur_ndpp_fpga_header.vh]
read_verilog -library xil_defaultlib {
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/fifo_ram/asfifo_user.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/base_demo/axi_stream_downsize.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/base_demo/axi_stream_noready_register.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/base_demo/axi_stream_register.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/base_demo/axi_stream_upsize.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/base_demo/base_demo.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/base_demo/base_demo_regfile.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/base_demo/cross_domain.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/fifo_ram/fifo_fwft_adapter_user.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/fifo_ram/general_asfifo_fwft_user.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/fifo_ram/general_sdpram_dc_user.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/base_demo/macrx2userdma.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/base_demo/packet_loss.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/user_xc_inst.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/base_demo/userdma2mactx.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/fifo_ram/xilinx_sdpram_dc_user.v
  /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/rtl/yusur_ndpp_x1100.v
}
read_ip -quiet /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.srcs/sources_1/ip/ila_user_xc_inst/ila_user_xc_inst.xci
set_property used_in_synthesis false [get_files -all /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/ila_user_xc_inst/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/ila_user_xc_inst/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/ila_user_xc_inst/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.gen/sources_1/ip/ila_user_xc_inst/ila_user_xc_inst_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/xdc/yusur_ndpp_x1100.xdc
set_property used_in_implementation false [get_files /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/xdc/yusur_ndpp_x1100.xdc]

read_xdc /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/xdc/yusur_ndpp_user_logic.xdc
set_property used_in_implementation false [get_files /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/xdc/yusur_ndpp_user_logic.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /hdd-data/zhaomj/fae_zmj/wukuangqihuo_20250311/NDPP-FDK-Basic-XSeries-V1.1.0.8/NDPP-FDK/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.srcs/utils_1/imports/synth_1/yusur_ndpp_x1100.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top yusur_ndpp_x1100 -part xcku15p_CIV-ffve1517-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef yusur_ndpp_x1100.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file yusur_ndpp_x1100_utilization_synth.rpt -pb yusur_ndpp_x1100_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
