# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.runs/synth_1/yusur_ndpp_x1100.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.maxThreads 16
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku15p_CIV-ffve1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.cache/wt [current_project]
set_property parent.project_path /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files -quiet /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/ip/yusur_ndpp_fdk/yusur_ndpp_x1100.dcp
set_property used_in_implementation false [get_files /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/ip/yusur_ndpp_fdk/yusur_ndpp_x1100.dcp]
read_verilog /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/rtl/yusur_ndpp_fpga_header.vh
set_property is_global_include true [get_files /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/rtl/yusur_ndpp_fpga_header.vh]
read_verilog -library xil_defaultlib {
  /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/rtl/design_1.v
  /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/rtl/design_1_wrapper.v
  /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/rtl/ndpp_regfile.v
  /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/rtl/ndpp_wrapper.v
  /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/rtl/yusur_ndpp_x1100.v
}
read_ip -quiet /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/ip/design_1_axis_data_fifo_2_0/design_1_axis_data_fifo_2_0.xci
set_property used_in_implementation false [get_files -all /root/DOWNLOAD/SWIFT/project_1.gen/sources_1/bd/design_1/ip/design_1_axis_data_fifo_2_0/design_1_axis_data_fifo_2_0_ooc.xdc]

read_ip -quiet /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/ip/design_1_axis_data_fifo_3_0/design_1_axis_data_fifo_3_0.xci
set_property used_in_implementation false [get_files -all /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/project_1.gen/sources_1/ip/design_1_axis_data_fifo_3_0/design_1_axis_data_fifo_3_0_ooc.xdc]

read_ip -quiet /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/ip/design_1_axis_data_fifo_0_2/design_1_axis_data_fifo_0_2.xci
set_property used_in_implementation false [get_files -all /root/DOWNLOAD/SWIFT/project_1.gen/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_2/design_1_axis_data_fifo_0_2_ooc.xdc]

read_ip -quiet /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/ip/design_1_yusur_hash_allocation_0_0/design_1_yusur_hash_allocation_0_0.xci
set_property used_in_implementation false [get_files -all /root/DOWNLOAD/SWIFT/project_1.gen/sources_1/bd/design_1/ip/design_1_yusur_hash_allocation_0_0/constraints/yusur_hash_allocation_ooc.xdc]

read_ip -quiet /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/ip/design_1_yusur_udp_filter_0_0/design_1_yusur_udp_filter_0_0.xci
set_property used_in_implementation false [get_files -all /root/DOWNLOAD/SWIFT/project_1.gen/sources_1/bd/design_1/ip/design_1_yusur_udp_filter_0_0/constraints/yusur_udp_filter_ooc.xdc]

read_ip -quiet /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/ip/design_1_axis_data_fifo_0_3/design_1_axis_data_fifo_0_3.xci
set_property used_in_implementation false [get_files -all /root/DOWNLOAD/SWIFT/project_1.gen/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_3/design_1_axis_data_fifo_0_3_ooc.xdc]

read_ip -quiet /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/ip/design_1_axis_dwidth_converter_0_0/design_1_axis_dwidth_converter_0_0.xci
set_property used_in_implementation false [get_files -all /root/DOWNLOAD/SWIFT/project_1.gen/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_0_0/design_1_axis_dwidth_converter_0_0_ooc.xdc]

read_ip -quiet /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property used_in_implementation false [get_files -all /root/DOWNLOAD/SWIFT/project_1.gen/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/xdc/yusur_ndpp_x1100.xdc
set_property used_in_implementation false [get_files /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/xdc/yusur_ndpp_x1100.xdc]

read_xdc /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/xdc/yusur_ndpp_user_logic.xdc
set_property used_in_implementation false [get_files /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/xdc/yusur_ndpp_user_logic.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /root/DOWNLOAD/SWIFT/pkg-20260220/pkg/NDPP-FDK-X1100/X1100/prj/yusur_ndpp_x1100/yusur_ndpp_x1100.srcs/utils_1/imports/synth_1/yusur_ndpp_x1100.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top yusur_ndpp_x1100 -part xcku15p_CIV-ffve1517-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef yusur_ndpp_x1100.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file yusur_ndpp_x1100_utilization_synth.rpt -pb yusur_ndpp_x1100_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
