// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="yusur_udp_filter_yusur_udp_filter,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku15p_CIV-ffve1517-2-e,HLS_INPUT_CLOCK=3.500000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.935333,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1009,HLS_SYN_LUT=759,HLS_VERSION=2022_2}" *)

module yusur_udp_filter (
        ap_clk,
        ap_rst_n,
        i_axiu_udp_param_TDATA,
        i_axiu_udp_param_TVALID,
        i_axiu_udp_param_TREADY,
        i_axiu_stream_data_TDATA,
        i_axiu_stream_data_TVALID,
        i_axiu_stream_data_TREADY,
        i_axiu_stream_data_TKEEP,
        i_axiu_stream_data_TSTRB,
        i_axiu_stream_data_TLAST,
        o_axiu_key_TDATA,
        o_axiu_key_TVALID,
        o_axiu_key_TREADY,
        o_axiu_stream_data_TDATA,
        o_axiu_stream_data_TVALID,
        o_axiu_stream_data_TREADY,
        o_axiu_stream_data_TKEEP,
        o_axiu_stream_data_TSTRB,
        o_axiu_stream_data_TLAST
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst_n;
input  [127:0] i_axiu_udp_param_TDATA;
input   i_axiu_udp_param_TVALID;
output   i_axiu_udp_param_TREADY;
input  [63:0] i_axiu_stream_data_TDATA;
input   i_axiu_stream_data_TVALID;
output   i_axiu_stream_data_TREADY;
input  [7:0] i_axiu_stream_data_TKEEP;
input  [7:0] i_axiu_stream_data_TSTRB;
input  [0:0] i_axiu_stream_data_TLAST;
output  [79:0] o_axiu_key_TDATA;
output   o_axiu_key_TVALID;
input   o_axiu_key_TREADY;
output  [63:0] o_axiu_stream_data_TDATA;
output   o_axiu_stream_data_TVALID;
input   o_axiu_stream_data_TREADY;
output  [7:0] o_axiu_stream_data_TKEEP;
output  [7:0] o_axiu_stream_data_TSTRB;
output  [0:0] o_axiu_stream_data_TLAST;

 reg    ap_rst_n_inv;
reg    i_axiu_udp_param_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] p_Result_s_fu_178_p5;
reg   [31:0] p_Result_s_reg_322;
wire   [31:0] p_Result_48_fu_230_p5;
reg   [31:0] p_Result_48_reg_327;
wire   [15:0] p_Result_49_fu_262_p3;
reg   [15:0] p_Result_49_reg_332;
wire   [15:0] p_Result_50_fu_290_p3;
reg   [15:0] p_Result_50_reg_337;
wire   [0:0] cmp_i_i421_fu_298_p2;
reg   [0:0] cmp_i_i421_reg_342;
wire   [0:0] cmp_i_i412_fu_304_p2;
reg   [0:0] cmp_i_i412_reg_347;
wire   [0:0] cmp_i_i403_fu_310_p2;
reg   [0:0] cmp_i_i403_reg_352;
wire   [0:0] cmp_i_i394_fu_316_p2;
reg   [0:0] cmp_i_i394_reg_357;
wire    grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_start;
wire    grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_done;
wire    grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_idle;
wire    grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_ready;
wire    grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_i_axiu_stream_data_TREADY;
wire   [79:0] grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_key_TDATA;
wire    grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_key_TVALID;
wire    grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_key_TREADY;
wire   [63:0] grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TDATA;
wire    grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TVALID;
wire    grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TREADY;
wire   [7:0] grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TKEEP;
wire   [7:0] grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TSTRB;
wire   [0:0] grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TLAST;
reg    grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [7:0] trunc_ln628_fu_174_p1;
wire   [7:0] tmp_12_fu_164_p4;
wire   [7:0] tmp_s_fu_154_p4;
wire   [7:0] tmp1_fu_144_p4;
wire   [7:0] tmp_16_fu_220_p4;
wire   [7:0] tmp_15_fu_210_p4;
wire   [7:0] tmp_14_fu_200_p4;
wire   [7:0] tmp_13_fu_190_p4;
wire   [7:0] tmp_17_fu_252_p4;
wire   [7:0] tmp_11_fu_242_p4;
wire   [7:0] tmp_19_fu_280_p4;
wire   [7:0] tmp_18_fu_270_p4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_o_axiu_key_U_apdone_blk;
wire    regslice_both_o_axiu_stream_data_V_data_V_U_apdone_blk;
reg    ap_block_state4;
wire    ap_CS_fsm_state4;
wire    regslice_both_i_axiu_udp_param_U_apdone_blk;
wire   [127:0] i_axiu_udp_param_TDATA_int_regslice;
wire    i_axiu_udp_param_TVALID_int_regslice;
reg    i_axiu_udp_param_TREADY_int_regslice;
wire    regslice_both_i_axiu_udp_param_U_ack_in;
wire    regslice_both_i_axiu_stream_data_V_data_V_U_apdone_blk;
wire   [63:0] i_axiu_stream_data_TDATA_int_regslice;
wire    i_axiu_stream_data_TVALID_int_regslice;
reg    i_axiu_stream_data_TREADY_int_regslice;
wire    regslice_both_i_axiu_stream_data_V_data_V_U_ack_in;
wire    regslice_both_i_axiu_stream_data_V_keep_V_U_apdone_blk;
wire   [7:0] i_axiu_stream_data_TKEEP_int_regslice;
wire    regslice_both_i_axiu_stream_data_V_keep_V_U_vld_out;
wire    regslice_both_i_axiu_stream_data_V_keep_V_U_ack_in;
wire    regslice_both_i_axiu_stream_data_V_strb_V_U_apdone_blk;
wire   [7:0] i_axiu_stream_data_TSTRB_int_regslice;
wire    regslice_both_i_axiu_stream_data_V_strb_V_U_vld_out;
wire    regslice_both_i_axiu_stream_data_V_strb_V_U_ack_in;
wire    regslice_both_i_axiu_stream_data_V_last_V_U_apdone_blk;
wire   [0:0] i_axiu_stream_data_TLAST_int_regslice;
wire    regslice_both_i_axiu_stream_data_V_last_V_U_vld_out;
wire    regslice_both_i_axiu_stream_data_V_last_V_U_ack_in;
wire    o_axiu_key_TREADY_int_regslice;
wire    regslice_both_o_axiu_key_U_vld_out;
wire    o_axiu_stream_data_TVALID_int_regslice;
wire    o_axiu_stream_data_TREADY_int_regslice;
wire    regslice_both_o_axiu_stream_data_V_data_V_U_vld_out;
wire    regslice_both_o_axiu_stream_data_V_keep_V_U_apdone_blk;
wire    regslice_both_o_axiu_stream_data_V_keep_V_U_ack_in_dummy;
wire    regslice_both_o_axiu_stream_data_V_keep_V_U_vld_out;
wire    regslice_both_o_axiu_stream_data_V_strb_V_U_apdone_blk;
wire    regslice_both_o_axiu_stream_data_V_strb_V_U_ack_in_dummy;
wire    regslice_both_o_axiu_stream_data_V_strb_V_U_vld_out;
wire    regslice_both_o_axiu_stream_data_V_last_V_U_apdone_blk;
wire    regslice_both_o_axiu_stream_data_V_last_V_U_ack_in_dummy;
wire    regslice_both_o_axiu_stream_data_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_start_reg = 1'b0;
end

yusur_udp_filter_yusur_udp_filter_Pipeline_LOOP_WORKING grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_start),
    .ap_done(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_done),
    .ap_idle(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_idle),
    .ap_ready(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_ready),
    .i_axiu_stream_data_TDATA(i_axiu_stream_data_TDATA_int_regslice),
    .i_axiu_stream_data_TVALID(i_axiu_stream_data_TVALID_int_regslice),
    .i_axiu_stream_data_TREADY(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_i_axiu_stream_data_TREADY),
    .i_axiu_stream_data_TKEEP(i_axiu_stream_data_TKEEP_int_regslice),
    .i_axiu_stream_data_TSTRB(i_axiu_stream_data_TSTRB_int_regslice),
    .i_axiu_stream_data_TLAST(i_axiu_stream_data_TLAST_int_regslice),
    .p_Result_s(p_Result_s_reg_322),
    .cmp_i_i421(cmp_i_i421_reg_342),
    .p_Result_1(p_Result_48_reg_327),
    .cmp_i_i412(cmp_i_i412_reg_347),
    .p_Result_2(p_Result_49_reg_332),
    .cmp_i_i403(cmp_i_i403_reg_352),
    .p_Result_3(p_Result_50_reg_337),
    .cmp_i_i394(cmp_i_i394_reg_357),
    .o_axiu_key_TDATA(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_key_TDATA),
    .o_axiu_key_TVALID(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_key_TVALID),
    .o_axiu_key_TREADY(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_key_TREADY),
    .o_axiu_stream_data_TDATA(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TDATA),
    .o_axiu_stream_data_TVALID(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TVALID),
    .o_axiu_stream_data_TREADY(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TREADY),
    .o_axiu_stream_data_TKEEP(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TKEEP),
    .o_axiu_stream_data_TSTRB(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TSTRB),
    .o_axiu_stream_data_TLAST(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TLAST)
);

yusur_udp_filter_regslice_both #(
    .DataWidth( 128 ))
regslice_both_i_axiu_udp_param_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_axiu_udp_param_TDATA),
    .vld_in(i_axiu_udp_param_TVALID),
    .ack_in(regslice_both_i_axiu_udp_param_U_ack_in),
    .data_out(i_axiu_udp_param_TDATA_int_regslice),
    .vld_out(i_axiu_udp_param_TVALID_int_regslice),
    .ack_out(i_axiu_udp_param_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_udp_param_U_apdone_blk)
);

yusur_udp_filter_regslice_both #(
    .DataWidth( 64 ))
regslice_both_i_axiu_stream_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_axiu_stream_data_TDATA),
    .vld_in(i_axiu_stream_data_TVALID),
    .ack_in(regslice_both_i_axiu_stream_data_V_data_V_U_ack_in),
    .data_out(i_axiu_stream_data_TDATA_int_regslice),
    .vld_out(i_axiu_stream_data_TVALID_int_regslice),
    .ack_out(i_axiu_stream_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_stream_data_V_data_V_U_apdone_blk)
);

yusur_udp_filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_i_axiu_stream_data_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_axiu_stream_data_TKEEP),
    .vld_in(i_axiu_stream_data_TVALID),
    .ack_in(regslice_both_i_axiu_stream_data_V_keep_V_U_ack_in),
    .data_out(i_axiu_stream_data_TKEEP_int_regslice),
    .vld_out(regslice_both_i_axiu_stream_data_V_keep_V_U_vld_out),
    .ack_out(i_axiu_stream_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_stream_data_V_keep_V_U_apdone_blk)
);

yusur_udp_filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_i_axiu_stream_data_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_axiu_stream_data_TSTRB),
    .vld_in(i_axiu_stream_data_TVALID),
    .ack_in(regslice_both_i_axiu_stream_data_V_strb_V_U_ack_in),
    .data_out(i_axiu_stream_data_TSTRB_int_regslice),
    .vld_out(regslice_both_i_axiu_stream_data_V_strb_V_U_vld_out),
    .ack_out(i_axiu_stream_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_stream_data_V_strb_V_U_apdone_blk)
);

yusur_udp_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_i_axiu_stream_data_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_axiu_stream_data_TLAST),
    .vld_in(i_axiu_stream_data_TVALID),
    .ack_in(regslice_both_i_axiu_stream_data_V_last_V_U_ack_in),
    .data_out(i_axiu_stream_data_TLAST_int_regslice),
    .vld_out(regslice_both_i_axiu_stream_data_V_last_V_U_vld_out),
    .ack_out(i_axiu_stream_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_axiu_stream_data_V_last_V_U_apdone_blk)
);

yusur_udp_filter_regslice_both #(
    .DataWidth( 80 ))
regslice_both_o_axiu_key_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_key_TDATA),
    .vld_in(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_key_TVALID),
    .ack_in(o_axiu_key_TREADY_int_regslice),
    .data_out(o_axiu_key_TDATA),
    .vld_out(regslice_both_o_axiu_key_U_vld_out),
    .ack_out(o_axiu_key_TREADY),
    .apdone_blk(regslice_both_o_axiu_key_U_apdone_blk)
);

yusur_udp_filter_regslice_both #(
    .DataWidth( 64 ))
regslice_both_o_axiu_stream_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TDATA),
    .vld_in(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TVALID),
    .ack_in(o_axiu_stream_data_TREADY_int_regslice),
    .data_out(o_axiu_stream_data_TDATA),
    .vld_out(regslice_both_o_axiu_stream_data_V_data_V_U_vld_out),
    .ack_out(o_axiu_stream_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_stream_data_V_data_V_U_apdone_blk)
);

yusur_udp_filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_o_axiu_stream_data_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TKEEP),
    .vld_in(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TVALID),
    .ack_in(regslice_both_o_axiu_stream_data_V_keep_V_U_ack_in_dummy),
    .data_out(o_axiu_stream_data_TKEEP),
    .vld_out(regslice_both_o_axiu_stream_data_V_keep_V_U_vld_out),
    .ack_out(o_axiu_stream_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_stream_data_V_keep_V_U_apdone_blk)
);

yusur_udp_filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_o_axiu_stream_data_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TSTRB),
    .vld_in(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TVALID),
    .ack_in(regslice_both_o_axiu_stream_data_V_strb_V_U_ack_in_dummy),
    .data_out(o_axiu_stream_data_TSTRB),
    .vld_out(regslice_both_o_axiu_stream_data_V_strb_V_U_vld_out),
    .ack_out(o_axiu_stream_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_stream_data_V_strb_V_U_apdone_blk)
);

yusur_udp_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_o_axiu_stream_data_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TLAST),
    .vld_in(grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TVALID),
    .ack_in(regslice_both_o_axiu_stream_data_V_last_V_U_ack_in_dummy),
    .data_out(o_axiu_stream_data_TLAST),
    .vld_out(regslice_both_o_axiu_stream_data_V_last_V_U_vld_out),
    .ack_out(o_axiu_stream_data_TREADY),
    .apdone_blk(regslice_both_o_axiu_stream_data_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_start_reg <= 1'b1;
        end else if ((grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_ready == 1'b1)) begin
            grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cmp_i_i394_reg_357 <= cmp_i_i394_fu_316_p2;
        cmp_i_i403_reg_352 <= cmp_i_i403_fu_310_p2;
        cmp_i_i412_reg_347 <= cmp_i_i412_fu_304_p2;
        cmp_i_i421_reg_342 <= cmp_i_i421_fu_298_p2;
        p_Result_48_reg_327 <= p_Result_48_fu_230_p5;
        p_Result_49_reg_332 <= p_Result_49_fu_262_p3;
        p_Result_50_reg_337 <= p_Result_50_fu_290_p3;
        p_Result_s_reg_322 <= p_Result_s_fu_178_p5;
    end
end

always @ (*) begin
    if ((i_axiu_udp_param_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_o_axiu_stream_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_o_axiu_key_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_axiu_stream_data_TREADY_int_regslice = grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_i_axiu_stream_data_TREADY;
    end else begin
        i_axiu_stream_data_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        i_axiu_udp_param_TDATA_blk_n = i_axiu_udp_param_TVALID_int_regslice;
    end else begin
        i_axiu_udp_param_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((i_axiu_udp_param_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_axiu_udp_param_TREADY_int_regslice = 1'b1;
    end else begin
        i_axiu_udp_param_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((i_axiu_udp_param_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((regslice_both_o_axiu_stream_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_o_axiu_key_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state4 = ((regslice_both_o_axiu_stream_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_o_axiu_key_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp_i_i394_fu_316_p2 = ((p_Result_50_fu_290_p3 == 16'd0) ? 1'b1 : 1'b0);

assign cmp_i_i403_fu_310_p2 = ((p_Result_49_fu_262_p3 == 16'd0) ? 1'b1 : 1'b0);

assign cmp_i_i412_fu_304_p2 = ((p_Result_48_fu_230_p5 == 32'd0) ? 1'b1 : 1'b0);

assign cmp_i_i421_fu_298_p2 = ((p_Result_s_fu_178_p5 == 32'd0) ? 1'b1 : 1'b0);

assign grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_start = grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_ap_start_reg;

assign grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_key_TREADY = (o_axiu_key_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TREADY = (o_axiu_stream_data_TREADY_int_regslice & ap_CS_fsm_state3);

assign i_axiu_stream_data_TREADY = regslice_both_i_axiu_stream_data_V_data_V_U_ack_in;

assign i_axiu_udp_param_TREADY = regslice_both_i_axiu_udp_param_U_ack_in;

assign o_axiu_key_TVALID = regslice_both_o_axiu_key_U_vld_out;

assign o_axiu_stream_data_TVALID = regslice_both_o_axiu_stream_data_V_data_V_U_vld_out;

assign o_axiu_stream_data_TVALID_int_regslice = grp_yusur_udp_filter_Pipeline_LOOP_WORKING_fu_114_o_axiu_stream_data_TVALID;

assign p_Result_48_fu_230_p5 = {{{{tmp_16_fu_220_p4}, {tmp_15_fu_210_p4}}, {tmp_14_fu_200_p4}}, {tmp_13_fu_190_p4}};

assign p_Result_49_fu_262_p3 = {{tmp_17_fu_252_p4}, {tmp_11_fu_242_p4}};

assign p_Result_50_fu_290_p3 = {{tmp_19_fu_280_p4}, {tmp_18_fu_270_p4}};

assign p_Result_s_fu_178_p5 = {{{{trunc_ln628_fu_174_p1}, {tmp_12_fu_164_p4}}, {tmp_s_fu_154_p4}}, {tmp1_fu_144_p4}};

assign tmp1_fu_144_p4 = {{i_axiu_udp_param_TDATA_int_regslice[31:24]}};

assign tmp_11_fu_242_p4 = {{i_axiu_udp_param_TDATA_int_regslice[79:72]}};

assign tmp_12_fu_164_p4 = {{i_axiu_udp_param_TDATA_int_regslice[15:8]}};

assign tmp_13_fu_190_p4 = {{i_axiu_udp_param_TDATA_int_regslice[63:56]}};

assign tmp_14_fu_200_p4 = {{i_axiu_udp_param_TDATA_int_regslice[55:48]}};

assign tmp_15_fu_210_p4 = {{i_axiu_udp_param_TDATA_int_regslice[47:40]}};

assign tmp_16_fu_220_p4 = {{i_axiu_udp_param_TDATA_int_regslice[39:32]}};

assign tmp_17_fu_252_p4 = {{i_axiu_udp_param_TDATA_int_regslice[71:64]}};

assign tmp_18_fu_270_p4 = {{i_axiu_udp_param_TDATA_int_regslice[111:104]}};

assign tmp_19_fu_280_p4 = {{i_axiu_udp_param_TDATA_int_regslice[103:96]}};

assign tmp_s_fu_154_p4 = {{i_axiu_udp_param_TDATA_int_regslice[23:16]}};

assign trunc_ln628_fu_174_p1 = i_axiu_udp_param_TDATA_int_regslice[7:0];


reg find_kernel_block = 0;
// synthesis translate_off
`include "yusur_udp_filter_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //yusur_udp_filter

