// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module yusur_udp_filter_yusur_udp_filter_Pipeline_LOOP_WORKING (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i_axiu_stream_data_TDATA,
        i_axiu_stream_data_TVALID,
        i_axiu_stream_data_TREADY,
        i_axiu_stream_data_TKEEP,
        i_axiu_stream_data_TSTRB,
        i_axiu_stream_data_TLAST,
        p_Result_s,
        cmp_i_i421,
        p_Result_1,
        cmp_i_i412,
        p_Result_2,
        cmp_i_i403,
        p_Result_3,
        cmp_i_i394,
        o_axiu_key_TDATA,
        o_axiu_key_TVALID,
        o_axiu_key_TREADY,
        o_axiu_stream_data_TDATA,
        o_axiu_stream_data_TVALID,
        o_axiu_stream_data_TREADY,
        o_axiu_stream_data_TKEEP,
        o_axiu_stream_data_TSTRB,
        o_axiu_stream_data_TLAST
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] i_axiu_stream_data_TDATA;
input   i_axiu_stream_data_TVALID;
output   i_axiu_stream_data_TREADY;
input  [7:0] i_axiu_stream_data_TKEEP;
input  [7:0] i_axiu_stream_data_TSTRB;
input  [0:0] i_axiu_stream_data_TLAST;
input  [31:0] p_Result_s;
input  [0:0] cmp_i_i421;
input  [31:0] p_Result_1;
input  [0:0] cmp_i_i412;
input  [15:0] p_Result_2;
input  [0:0] cmp_i_i403;
input  [15:0] p_Result_3;
input  [0:0] cmp_i_i394;
output  [79:0] o_axiu_key_TDATA;
output   o_axiu_key_TVALID;
input   o_axiu_key_TREADY;
output  [63:0] o_axiu_stream_data_TDATA;
output   o_axiu_stream_data_TVALID;
input   o_axiu_stream_data_TREADY;
output  [7:0] o_axiu_stream_data_TKEEP;
output  [7:0] o_axiu_stream_data_TSTRB;
output  [0:0] o_axiu_stream_data_TLAST;

reg ap_done;
reg ap_idle;
reg i_axiu_stream_data_TREADY;
reg o_axiu_key_TVALID;
reg o_axiu_stream_data_TVALID;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    i_axiu_stream_data_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] and_ln65_fu_619_p2;
reg    o_axiu_key_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] or_ln117_reg_1361;
reg   [0:0] and_ln163_4_reg_1365;
reg    o_axiu_stream_data_TDATA_blk_n;
reg   [0:0] frame_flag_1_reg_494;
reg   [0:0] icmp_ln184_reg_1419;
reg   [0:0] match_flag_21796_reg_505;
reg   [0:0] match_flag_reg_382;
reg   [0:0] frame_flag_reg_393;
reg   [0:0] match_flag_3_reg_543;
reg   [0:0] frame_flag_3_reg_558;
wire   [7:0] element_cnt_5_load_fu_601_p1;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op145_write_state3;
reg    ap_predicate_op146_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln117_fu_928_p2;
wire   [0:0] and_ln163_4_fu_1083_p2;
reg   [7:0] tmp_s_reg_1369;
reg   [7:0] tmp_2_reg_1374;
reg   [7:0] tmp_3_reg_1379;
reg   [7:0] tmp_4_reg_1384;
reg   [7:0] tmp_5_reg_1389;
reg   [7:0] tmp_6_reg_1394;
reg   [7:0] tmp_7_reg_1399;
reg   [7:0] tmp_8_reg_1404;
reg   [7:0] tmp_9_reg_1409;
reg   [7:0] tmp_10_reg_1414;
wire   [0:0] icmp_ln184_fu_1189_p2;
reg   [0:0] ap_phi_mux_frame_flag_1_phi_fu_497_p4;
wire   [63:0] curr_udp_data_V_fu_1195_p1;
reg   [63:0] curr_udp_data_V_reg_1423;
wire   [7:0] curr_udp_keep_V_fu_1199_p1;
reg   [7:0] curr_udp_keep_V_reg_1428;
wire   [0:0] curr_udp_last_V_fu_1203_p3;
reg   [0:0] curr_udp_last_V_reg_1433;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_match_flag_phi_fu_386_p4;
reg   [0:0] ap_phi_mux_frame_flag_phi_fu_397_p4;
reg   [639:0] ap_phi_mux_batch_data_V_10_phi_fu_407_p20;
wire   [639:0] p_Result_45_fu_853_p5;
wire   [639:0] ap_phi_reg_pp0_iter0_batch_data_V_10_reg_404;
wire   [639:0] p_Result_43_fu_645_p5;
wire   [639:0] p_Result_41_fu_671_p5;
wire   [639:0] p_Result_39_fu_697_p5;
wire   [639:0] p_Result_37_fu_723_p5;
wire   [639:0] p_Result_35_fu_749_p5;
wire   [639:0] p_Result_33_fu_775_p5;
wire   [639:0] p_Result_31_fu_801_p5;
wire   [639:0] p_Result_29_fu_827_p5;
wire   [639:0] p_Result_26_fu_879_p5;
reg   [89:0] ap_phi_mux_mark_data_V_10_phi_fu_432_p20;
wire   [89:0] p_Result_46_fu_866_p5;
wire   [89:0] ap_phi_reg_pp0_iter0_mark_data_V_10_reg_429;
wire   [89:0] p_Result_44_fu_658_p5;
wire   [89:0] p_Result_42_fu_684_p5;
wire   [89:0] p_Result_40_fu_710_p5;
wire   [89:0] p_Result_38_fu_736_p5;
wire   [89:0] p_Result_36_fu_762_p5;
wire   [89:0] p_Result_34_fu_788_p5;
wire   [89:0] p_Result_32_fu_814_p5;
wire   [89:0] p_Result_30_fu_840_p5;
wire   [89:0] p_Result_27_fu_892_p5;
reg   [639:0] ap_phi_mux_batch_data_V_16_phi_fu_457_p4;
wire   [639:0] ap_phi_reg_pp0_iter0_batch_data_V_16_reg_454;
reg   [89:0] ap_phi_mux_mark_data_V_16_phi_fu_467_p4;
wire   [89:0] ap_phi_reg_pp0_iter0_mark_data_V_16_reg_464;
reg   [7:0] ap_phi_mux_element_cnt_1_phi_fu_477_p4;
wire   [7:0] element_cnt_6_fu_905_p2;
wire   [7:0] ap_phi_reg_pp0_iter0_element_cnt_1_reg_474;
reg   [0:0] ap_phi_mux_match_flag_1_phi_fu_486_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_match_flag_1_reg_483;
wire   [0:0] or_ln117_1_fu_940_p2;
wire   [0:0] ap_phi_reg_pp0_iter0_frame_flag_1_reg_494;
reg   [0:0] ap_phi_mux_match_flag_21796_phi_fu_508_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_match_flag_21796_reg_505;
reg   [639:0] ap_phi_mux_batch_data_V_13_phi_fu_520_p6;
wire   [639:0] zext_ln998_fu_1221_p1;
wire   [639:0] ap_phi_reg_pp0_iter0_batch_data_V_13_reg_517;
reg   [89:0] ap_phi_mux_mark_data_V_13_phi_fu_533_p6;
wire   [89:0] zext_ln998_1_fu_1236_p1;
wire   [89:0] ap_phi_reg_pp0_iter0_mark_data_V_13_reg_530;
wire   [0:0] match_flag_2_fu_1255_p2;
wire   [0:0] ap_phi_reg_pp0_iter0_match_flag_3_reg_543;
wire   [0:0] frame_flag_2_fu_1248_p2;
wire   [0:0] ap_phi_reg_pp0_iter0_frame_flag_3_reg_558;
reg   [7:0] ap_phi_mux_element_cnt_2_phi_fu_576_p6;
wire   [7:0] element_cnt_7_fu_1241_p2;
wire   [7:0] ap_phi_reg_pp0_iter0_element_cnt_2_reg_573;
reg   [7:0] element_cnt_fu_272;
reg   [89:0] p_Val2_s_fu_276;
reg   [639:0] p_Val2_1_fu_280;
wire   [0:0] tmp_nbreadreq_fu_332_p6;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln65_fu_613_p2;
wire   [8:0] p_Result_28_fu_637_p3;
wire   [4:0] tmp_1_fu_912_p4;
wire   [0:0] icmp_ln117_fu_922_p2;
wire   [0:0] xor_ln117_fu_934_p2;
wire   [31:0] get_src_ip_V_fu_967_p4;
wire   [0:0] icmp_ln1019_fu_1007_p2;
wire   [31:0] get_dst_ip_V_fu_977_p4;
wire   [0:0] icmp_ln1019_1_fu_1017_p2;
wire   [15:0] get_src_port_V_fu_987_p4;
wire   [0:0] icmp_ln1019_2_fu_1027_p2;
wire   [15:0] get_dst_port_V_fu_997_p4;
wire   [0:0] icmp_ln1019_3_fu_1037_p2;
wire   [23:0] get_eth_ip_type_V_fu_947_p4;
wire   [7:0] get_udp_type_V_fu_957_p4;
wire   [0:0] src_ip_match_fu_1012_p2;
wire   [0:0] icmp_ln1019_5_fu_1053_p2;
wire   [0:0] src_port_match_fu_1032_p2;
wire   [0:0] dst_port_match_fu_1042_p2;
wire   [0:0] and_ln163_2_fu_1065_p2;
wire   [0:0] dst_ip_match_fu_1022_p2;
wire   [0:0] and_ln163_fu_1059_p2;
wire   [0:0] icmp_ln1019_4_fu_1047_p2;
wire   [0:0] and_ln163_1_fu_1077_p2;
wire   [0:0] and_ln163_3_fu_1071_p2;
wire   [575:0] batch_data_V_fu_1211_p4;
wire   [80:0] mark_data_V_fu_1226_p4;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_803;
reg    ap_condition_212;
reg    ap_condition_195;
reg    ap_condition_324;
reg    ap_condition_329;
reg    ap_condition_315;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        element_cnt_fu_272 <= 8'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        element_cnt_fu_272 <= ap_phi_mux_element_cnt_2_phi_fu_576_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if (((1'd0 == and_ln163_4_fu_1083_p2) & (or_ln117_fu_928_p2 == 1'd0))) begin
            frame_flag_1_reg_494 <= 1'd1;
        end else if ((or_ln117_fu_928_p2 == 1'd1)) begin
            frame_flag_1_reg_494 <= or_ln117_1_fu_940_p2;
        end else if ((1'b1 == 1'b1)) begin
            frame_flag_1_reg_494 <= ap_phi_reg_pp0_iter0_frame_flag_1_reg_494;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((1'b1 == ap_condition_329)) begin
            frame_flag_3_reg_558 <= 1'd1;
        end else if ((1'b1 == ap_condition_324)) begin
            frame_flag_3_reg_558 <= 1'd0;
        end else if ((1'b1 == ap_condition_195)) begin
            frame_flag_3_reg_558 <= frame_flag_2_fu_1248_p2;
        end else if ((1'b1 == 1'b1)) begin
            frame_flag_3_reg_558 <= ap_phi_reg_pp0_iter0_frame_flag_3_reg_558;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        frame_flag_reg_393 <= frame_flag_3_reg_558;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        frame_flag_reg_393 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((1'b1 == ap_condition_315)) begin
            match_flag_21796_reg_505 <= ap_phi_mux_match_flag_1_phi_fu_486_p4;
        end else if (((1'd1 == and_ln163_4_fu_1083_p2) & (or_ln117_fu_928_p2 == 1'd0))) begin
            match_flag_21796_reg_505 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            match_flag_21796_reg_505 <= ap_phi_reg_pp0_iter0_match_flag_21796_reg_505;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((1'b1 == ap_condition_329)) begin
            match_flag_3_reg_543 <= ap_phi_mux_match_flag_21796_phi_fu_508_p4;
        end else if ((1'b1 == ap_condition_324)) begin
            match_flag_3_reg_543 <= ap_phi_mux_match_flag_1_phi_fu_486_p4;
        end else if ((1'b1 == ap_condition_195)) begin
            match_flag_3_reg_543 <= match_flag_2_fu_1255_p2;
        end else if ((1'b1 == 1'b1)) begin
            match_flag_3_reg_543 <= ap_phi_reg_pp0_iter0_match_flag_3_reg_543;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        match_flag_reg_382 <= match_flag_3_reg_543;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        match_flag_reg_382 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Val2_1_fu_280 <= 640'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Val2_1_fu_280 <= ap_phi_mux_batch_data_V_13_phi_fu_520_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Val2_s_fu_276 <= 90'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Val2_s_fu_276 <= ap_phi_mux_mark_data_V_13_phi_fu_533_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln117_fu_928_p2 == 1'd0))) begin
        and_ln163_4_reg_1365 <= and_ln163_4_fu_1083_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (icmp_ln184_fu_1189_p2 == 1'd0)) | ((1'd1 == and_ln163_4_fu_1083_p2) & (icmp_ln184_fu_1189_p2 == 1'd0) & (or_ln117_fu_928_p2 == 1'd0))))) begin
        curr_udp_data_V_reg_1423 <= curr_udp_data_V_fu_1195_p1;
        curr_udp_keep_V_reg_1428 <= curr_udp_keep_V_fu_1199_p1;
        curr_udp_last_V_reg_1433 <= ap_phi_mux_mark_data_V_16_phi_fu_467_p4[32'd8];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) | ((1'd1 == and_ln163_4_fu_1083_p2) & (or_ln117_fu_928_p2 == 1'd0))))) begin
        icmp_ln184_reg_1419 <= icmp_ln184_fu_1189_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln117_reg_1361 <= or_ln117_fu_928_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln163_4_fu_1083_p2) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln117_fu_928_p2 == 1'd0))) begin
        tmp_10_reg_1414 <= {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[383:376]}};
        tmp_2_reg_1374 <= {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[447:440]}};
        tmp_3_reg_1379 <= {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[439:432]}};
        tmp_4_reg_1384 <= {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[431:424]}};
        tmp_5_reg_1389 <= {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[423:416]}};
        tmp_6_reg_1394 <= {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[415:408]}};
        tmp_7_reg_1399 <= {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[407:400]}};
        tmp_8_reg_1404 <= {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[399:392]}};
        tmp_9_reg_1409 <= {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[391:384]}};
        tmp_s_reg_1369 <= {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[455:448]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == and_ln65_fu_619_p2)) begin
        if ((1'b1 == ap_condition_803)) begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = p_Result_26_fu_879_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd1)) begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = p_Result_29_fu_827_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd2)) begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = p_Result_31_fu_801_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd3)) begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = p_Result_33_fu_775_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd4)) begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = p_Result_35_fu_749_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd5)) begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = p_Result_37_fu_723_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd6)) begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = p_Result_39_fu_697_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd7)) begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = p_Result_41_fu_671_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd8)) begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = p_Result_43_fu_645_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd9)) begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = p_Result_45_fu_853_p5;
        end else begin
            ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = ap_phi_reg_pp0_iter0_batch_data_V_10_reg_404;
        end
    end else begin
        ap_phi_mux_batch_data_V_10_phi_fu_407_p20 = ap_phi_reg_pp0_iter0_batch_data_V_10_reg_404;
    end
end

always @ (*) begin
    if ((((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd0) & (or_ln117_fu_928_p2 == 1'd1)) | ((1'd0 == and_ln163_4_fu_1083_p2) & (ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd0)) | ((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (icmp_ln184_fu_1189_p2 == 1'd1)) | ((1'd1 == and_ln163_4_fu_1083_p2) & (icmp_ln184_fu_1189_p2 == 1'd1) & (or_ln117_fu_928_p2 == 1'd0)))) begin
        ap_phi_mux_batch_data_V_13_phi_fu_520_p6 = ap_phi_mux_batch_data_V_16_phi_fu_457_p4;
    end else if ((((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (icmp_ln184_fu_1189_p2 == 1'd0)) | ((1'd1 == and_ln163_4_fu_1083_p2) & (icmp_ln184_fu_1189_p2 == 1'd0) & (or_ln117_fu_928_p2 == 1'd0)))) begin
        ap_phi_mux_batch_data_V_13_phi_fu_520_p6 = zext_ln998_fu_1221_p1;
    end else begin
        ap_phi_mux_batch_data_V_13_phi_fu_520_p6 = ap_phi_reg_pp0_iter0_batch_data_V_13_reg_517;
    end
end

always @ (*) begin
    if ((1'd0 == and_ln65_fu_619_p2)) begin
        ap_phi_mux_batch_data_V_16_phi_fu_457_p4 = p_Val2_1_fu_280;
    end else if ((1'd1 == and_ln65_fu_619_p2)) begin
        ap_phi_mux_batch_data_V_16_phi_fu_457_p4 = ap_phi_mux_batch_data_V_10_phi_fu_407_p20;
    end else begin
        ap_phi_mux_batch_data_V_16_phi_fu_457_p4 = ap_phi_reg_pp0_iter0_batch_data_V_16_reg_454;
    end
end

always @ (*) begin
    if ((1'd0 == and_ln65_fu_619_p2)) begin
        ap_phi_mux_element_cnt_1_phi_fu_477_p4 = element_cnt_fu_272;
    end else if ((1'd1 == and_ln65_fu_619_p2)) begin
        ap_phi_mux_element_cnt_1_phi_fu_477_p4 = element_cnt_6_fu_905_p2;
    end else begin
        ap_phi_mux_element_cnt_1_phi_fu_477_p4 = ap_phi_reg_pp0_iter0_element_cnt_1_reg_474;
    end
end

always @ (*) begin
    if ((((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (icmp_ln184_fu_1189_p2 == 1'd1)) | ((1'd1 == and_ln163_4_fu_1083_p2) & (icmp_ln184_fu_1189_p2 == 1'd1) & (or_ln117_fu_928_p2 == 1'd0)))) begin
        ap_phi_mux_element_cnt_2_phi_fu_576_p6 = 8'd0;
    end else if ((((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd0) & (or_ln117_fu_928_p2 == 1'd1)) | ((1'd0 == and_ln163_4_fu_1083_p2) & (ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd0)))) begin
        ap_phi_mux_element_cnt_2_phi_fu_576_p6 = ap_phi_mux_element_cnt_1_phi_fu_477_p4;
    end else if ((((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (icmp_ln184_fu_1189_p2 == 1'd0)) | ((1'd1 == and_ln163_4_fu_1083_p2) & (icmp_ln184_fu_1189_p2 == 1'd0) & (or_ln117_fu_928_p2 == 1'd0)))) begin
        ap_phi_mux_element_cnt_2_phi_fu_576_p6 = element_cnt_7_fu_1241_p2;
    end else begin
        ap_phi_mux_element_cnt_2_phi_fu_576_p6 = ap_phi_reg_pp0_iter0_element_cnt_2_reg_573;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln163_4_fu_1083_p2) & (or_ln117_fu_928_p2 == 1'd0))) begin
        ap_phi_mux_frame_flag_1_phi_fu_497_p4 = 1'd1;
    end else if ((or_ln117_fu_928_p2 == 1'd1)) begin
        ap_phi_mux_frame_flag_1_phi_fu_497_p4 = or_ln117_1_fu_940_p2;
    end else begin
        ap_phi_mux_frame_flag_1_phi_fu_497_p4 = ap_phi_reg_pp0_iter0_frame_flag_1_reg_494;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_frame_flag_phi_fu_397_p4 = frame_flag_3_reg_558;
    end else begin
        ap_phi_mux_frame_flag_phi_fu_397_p4 = frame_flag_reg_393;
    end
end

always @ (*) begin
    if ((1'd1 == and_ln65_fu_619_p2)) begin
        if ((1'b1 == ap_condition_803)) begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = p_Result_27_fu_892_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd1)) begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = p_Result_30_fu_840_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd2)) begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = p_Result_32_fu_814_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd3)) begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = p_Result_34_fu_788_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd4)) begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = p_Result_36_fu_762_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd5)) begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = p_Result_38_fu_736_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd6)) begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = p_Result_40_fu_710_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd7)) begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = p_Result_42_fu_684_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd8)) begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = p_Result_44_fu_658_p5;
        end else if ((element_cnt_5_load_fu_601_p1 == 8'd9)) begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = p_Result_46_fu_866_p5;
        end else begin
            ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = ap_phi_reg_pp0_iter0_mark_data_V_10_reg_429;
        end
    end else begin
        ap_phi_mux_mark_data_V_10_phi_fu_432_p20 = ap_phi_reg_pp0_iter0_mark_data_V_10_reg_429;
    end
end

always @ (*) begin
    if ((((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd0) & (or_ln117_fu_928_p2 == 1'd1)) | ((1'd0 == and_ln163_4_fu_1083_p2) & (ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd0)) | ((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (icmp_ln184_fu_1189_p2 == 1'd1)) | ((1'd1 == and_ln163_4_fu_1083_p2) & (icmp_ln184_fu_1189_p2 == 1'd1) & (or_ln117_fu_928_p2 == 1'd0)))) begin
        ap_phi_mux_mark_data_V_13_phi_fu_533_p6 = ap_phi_mux_mark_data_V_16_phi_fu_467_p4;
    end else if ((((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (icmp_ln184_fu_1189_p2 == 1'd0)) | ((1'd1 == and_ln163_4_fu_1083_p2) & (icmp_ln184_fu_1189_p2 == 1'd0) & (or_ln117_fu_928_p2 == 1'd0)))) begin
        ap_phi_mux_mark_data_V_13_phi_fu_533_p6 = zext_ln998_1_fu_1236_p1;
    end else begin
        ap_phi_mux_mark_data_V_13_phi_fu_533_p6 = ap_phi_reg_pp0_iter0_mark_data_V_13_reg_530;
    end
end

always @ (*) begin
    if ((1'd0 == and_ln65_fu_619_p2)) begin
        ap_phi_mux_mark_data_V_16_phi_fu_467_p4 = p_Val2_s_fu_276;
    end else if ((1'd1 == and_ln65_fu_619_p2)) begin
        ap_phi_mux_mark_data_V_16_phi_fu_467_p4 = ap_phi_mux_mark_data_V_10_phi_fu_432_p20;
    end else begin
        ap_phi_mux_mark_data_V_16_phi_fu_467_p4 = ap_phi_reg_pp0_iter0_mark_data_V_16_reg_464;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln163_4_fu_1083_p2) & (or_ln117_fu_928_p2 == 1'd0))) begin
        ap_phi_mux_match_flag_1_phi_fu_486_p4 = 1'd0;
    end else if ((or_ln117_fu_928_p2 == 1'd1)) begin
        ap_phi_mux_match_flag_1_phi_fu_486_p4 = ap_phi_mux_match_flag_phi_fu_386_p4;
    end else begin
        ap_phi_mux_match_flag_1_phi_fu_486_p4 = ap_phi_reg_pp0_iter0_match_flag_1_reg_483;
    end
end

always @ (*) begin
    if ((((1'd0 == and_ln163_4_fu_1083_p2) & (ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1)) | ((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (or_ln117_fu_928_p2 == 1'd1)))) begin
        ap_phi_mux_match_flag_21796_phi_fu_508_p4 = ap_phi_mux_match_flag_1_phi_fu_486_p4;
    end else if (((1'd1 == and_ln163_4_fu_1083_p2) & (or_ln117_fu_928_p2 == 1'd0))) begin
        ap_phi_mux_match_flag_21796_phi_fu_508_p4 = 1'd1;
    end else begin
        ap_phi_mux_match_flag_21796_phi_fu_508_p4 = ap_phi_reg_pp0_iter0_match_flag_21796_reg_505;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_match_flag_phi_fu_386_p4 = match_flag_3_reg_543;
    end else begin
        ap_phi_mux_match_flag_phi_fu_386_p4 = match_flag_reg_382;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln65_fu_619_p2) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_axiu_stream_data_TDATA_blk_n = i_axiu_stream_data_TVALID;
    end else begin
        i_axiu_stream_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln65_fu_619_p2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_axiu_stream_data_TREADY = 1'b1;
    end else begin
        i_axiu_stream_data_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln117_reg_1361 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'd1 == and_ln163_4_reg_1365) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        o_axiu_key_TDATA_blk_n = o_axiu_key_TREADY;
    end else begin
        o_axiu_key_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op145_write_state3 == 1'b1))) begin
        o_axiu_key_TVALID = 1'b1;
    end else begin
        o_axiu_key_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((match_flag_21796_reg_505 == 1'd1) & (icmp_ln184_reg_1419 == 1'd0) & (frame_flag_1_reg_494 == 1'd1)) | ((match_flag_21796_reg_505 == 1'd1) & (icmp_ln184_reg_1419 == 1'd0) & (or_ln117_reg_1361 == 1'd0) & (1'd1 == and_ln163_4_reg_1365))))) begin
        o_axiu_stream_data_TDATA_blk_n = o_axiu_stream_data_TREADY;
    end else begin
        o_axiu_stream_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op146_write_state3 == 1'b1))) begin
        o_axiu_stream_data_TVALID = 1'b1;
    end else begin
        o_axiu_stream_data_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln163_1_fu_1077_p2 = (icmp_ln1019_4_fu_1047_p2 & and_ln163_fu_1059_p2);

assign and_ln163_2_fu_1065_p2 = (src_port_match_fu_1032_p2 & dst_port_match_fu_1042_p2);

assign and_ln163_3_fu_1071_p2 = (dst_ip_match_fu_1022_p2 & and_ln163_2_fu_1065_p2);

assign and_ln163_4_fu_1083_p2 = (and_ln163_3_fu_1071_p2 & and_ln163_1_fu_1077_p2);

assign and_ln163_fu_1059_p2 = (src_ip_match_fu_1012_p2 & icmp_ln1019_5_fu_1053_p2);

assign and_ln65_fu_619_p2 = (tmp_nbreadreq_fu_332_p6 & icmp_ln65_fu_613_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((o_axiu_stream_data_TREADY == 1'b0) & (ap_predicate_op146_write_state3 == 1'b1)) | ((o_axiu_key_TREADY == 1'b0) & (ap_predicate_op145_write_state3 == 1'b1)))) | ((1'd1 == and_ln65_fu_619_p2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (i_axiu_stream_data_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((o_axiu_stream_data_TREADY == 1'b0) & (ap_predicate_op146_write_state3 == 1'b1)) | ((o_axiu_key_TREADY == 1'b0) & (ap_predicate_op145_write_state3 == 1'b1)))) | ((1'd1 == and_ln65_fu_619_p2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (i_axiu_stream_data_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((o_axiu_stream_data_TREADY == 1'b0) & (ap_predicate_op146_write_state3 == 1'b1)) | ((o_axiu_key_TREADY == 1'b0) & (ap_predicate_op145_write_state3 == 1'b1)))) | ((1'd1 == and_ln65_fu_619_p2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (i_axiu_stream_data_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((1'd1 == and_ln65_fu_619_p2) & (i_axiu_stream_data_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = (((o_axiu_stream_data_TREADY == 1'b0) & (ap_predicate_op146_write_state3 == 1'b1)) | ((o_axiu_key_TREADY == 1'b0) & (ap_predicate_op145_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((o_axiu_stream_data_TREADY == 1'b0) & (ap_predicate_op146_write_state3 == 1'b1)) | ((o_axiu_key_TREADY == 1'b0) & (ap_predicate_op145_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_condition_195 = (((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (icmp_ln184_fu_1189_p2 == 1'd0)) | ((1'd1 == and_ln163_4_fu_1083_p2) & (icmp_ln184_fu_1189_p2 == 1'd0) & (or_ln117_fu_928_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_212 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_315 = (((1'd0 == and_ln163_4_fu_1083_p2) & (ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1)) | ((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (or_ln117_fu_928_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_324 = (((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd0) & (or_ln117_fu_928_p2 == 1'd1)) | ((1'd0 == and_ln163_4_fu_1083_p2) & (ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd0)));
end

always @ (*) begin
    ap_condition_329 = (((ap_phi_mux_frame_flag_1_phi_fu_497_p4 == 1'd1) & (icmp_ln184_fu_1189_p2 == 1'd1)) | ((1'd1 == and_ln163_4_fu_1083_p2) & (icmp_ln184_fu_1189_p2 == 1'd1) & (or_ln117_fu_928_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_803 = (~(element_cnt_5_load_fu_601_p1 == 8'd1) & ~(element_cnt_5_load_fu_601_p1 == 8'd2) & ~(element_cnt_5_load_fu_601_p1 == 8'd3) & ~(element_cnt_5_load_fu_601_p1 == 8'd4) & ~(element_cnt_5_load_fu_601_p1 == 8'd5) & ~(element_cnt_5_load_fu_601_p1 == 8'd6) & ~(element_cnt_5_load_fu_601_p1 == 8'd7) & ~(element_cnt_5_load_fu_601_p1 == 8'd8) & ~(element_cnt_5_load_fu_601_p1 == 8'd9));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_batch_data_V_10_reg_404 = 'bx;

assign ap_phi_reg_pp0_iter0_batch_data_V_13_reg_517 = 'bx;

assign ap_phi_reg_pp0_iter0_batch_data_V_16_reg_454 = 'bx;

assign ap_phi_reg_pp0_iter0_element_cnt_1_reg_474 = 'bx;

assign ap_phi_reg_pp0_iter0_element_cnt_2_reg_573 = 'bx;

assign ap_phi_reg_pp0_iter0_frame_flag_1_reg_494 = 'bx;

assign ap_phi_reg_pp0_iter0_frame_flag_3_reg_558 = 'bx;

assign ap_phi_reg_pp0_iter0_mark_data_V_10_reg_429 = 'bx;

assign ap_phi_reg_pp0_iter0_mark_data_V_13_reg_530 = 'bx;

assign ap_phi_reg_pp0_iter0_mark_data_V_16_reg_464 = 'bx;

assign ap_phi_reg_pp0_iter0_match_flag_1_reg_483 = 'bx;

assign ap_phi_reg_pp0_iter0_match_flag_21796_reg_505 = 'bx;

assign ap_phi_reg_pp0_iter0_match_flag_3_reg_543 = 'bx;

always @ (*) begin
    ap_predicate_op145_write_state3 = ((or_ln117_reg_1361 == 1'd0) & (1'd1 == and_ln163_4_reg_1365));
end

always @ (*) begin
    ap_predicate_op146_write_state3 = (((match_flag_21796_reg_505 == 1'd1) & (icmp_ln184_reg_1419 == 1'd0) & (frame_flag_1_reg_494 == 1'd1)) | ((match_flag_21796_reg_505 == 1'd1) & (icmp_ln184_reg_1419 == 1'd0) & (or_ln117_reg_1361 == 1'd0) & (1'd1 == and_ln163_4_reg_1365)));
end

assign ap_ready = 1'b0;

assign batch_data_V_fu_1211_p4 = {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[639:64]}};

assign curr_udp_data_V_fu_1195_p1 = ap_phi_mux_batch_data_V_16_phi_fu_457_p4[63:0];

assign curr_udp_keep_V_fu_1199_p1 = ap_phi_mux_mark_data_V_16_phi_fu_467_p4[7:0];

assign curr_udp_last_V_fu_1203_p3 = ap_phi_mux_mark_data_V_16_phi_fu_467_p4[32'd8];

assign dst_ip_match_fu_1022_p2 = (icmp_ln1019_1_fu_1017_p2 | cmp_i_i412);

assign dst_port_match_fu_1042_p2 = (icmp_ln1019_3_fu_1037_p2 | cmp_i_i394);

assign element_cnt_5_load_fu_601_p1 = element_cnt_fu_272;

assign element_cnt_6_fu_905_p2 = (element_cnt_fu_272 + 8'd1);

assign element_cnt_7_fu_1241_p2 = ($signed(ap_phi_mux_element_cnt_1_phi_fu_477_p4) + $signed(8'd255));

assign frame_flag_2_fu_1248_p2 = (curr_udp_last_V_fu_1203_p3 ^ 1'd1);

assign get_dst_ip_V_fu_977_p4 = {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[271:240]}};

assign get_dst_port_V_fu_997_p4 = {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[303:288]}};

assign get_eth_ip_type_V_fu_947_p4 = {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[119:96]}};

assign get_src_ip_V_fu_967_p4 = {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[239:208]}};

assign get_src_port_V_fu_987_p4 = {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[287:272]}};

assign get_udp_type_V_fu_957_p4 = {{ap_phi_mux_batch_data_V_16_phi_fu_457_p4[191:184]}};

assign icmp_ln1019_1_fu_1017_p2 = ((get_dst_ip_V_fu_977_p4 == p_Result_1) ? 1'b1 : 1'b0);

assign icmp_ln1019_2_fu_1027_p2 = ((get_src_port_V_fu_987_p4 == p_Result_2) ? 1'b1 : 1'b0);

assign icmp_ln1019_3_fu_1037_p2 = ((get_dst_port_V_fu_997_p4 == p_Result_3) ? 1'b1 : 1'b0);

assign icmp_ln1019_4_fu_1047_p2 = ((get_eth_ip_type_V_fu_947_p4 == 24'd4521992) ? 1'b1 : 1'b0);

assign icmp_ln1019_5_fu_1053_p2 = ((get_udp_type_V_fu_957_p4 == 8'd17) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_1007_p2 = ((get_src_ip_V_fu_967_p4 == p_Result_s) ? 1'b1 : 1'b0);

assign icmp_ln117_fu_922_p2 = ((tmp_1_fu_912_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln184_fu_1189_p2 = ((ap_phi_mux_element_cnt_1_phi_fu_477_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_613_p2 = ((element_cnt_fu_272 < 8'd10) ? 1'b1 : 1'b0);

assign mark_data_V_fu_1226_p4 = {{ap_phi_mux_mark_data_V_16_phi_fu_467_p4[89:9]}};

assign match_flag_2_fu_1255_p2 = (frame_flag_2_fu_1248_p2 & ap_phi_mux_match_flag_21796_phi_fu_508_p4);

assign o_axiu_key_TDATA = {{{{{{{{{{tmp_10_reg_1414}, {tmp_9_reg_1409}}, {tmp_8_reg_1404}}, {tmp_7_reg_1399}}, {tmp_6_reg_1394}}, {tmp_5_reg_1389}}, {tmp_4_reg_1384}}, {tmp_3_reg_1379}}, {tmp_2_reg_1374}}, {tmp_s_reg_1369}};

assign o_axiu_stream_data_TDATA = curr_udp_data_V_reg_1423;

assign o_axiu_stream_data_TKEEP = curr_udp_keep_V_reg_1428;

assign o_axiu_stream_data_TLAST = curr_udp_last_V_reg_1433;

assign o_axiu_stream_data_TSTRB = 8'd0;

assign or_ln117_1_fu_940_p2 = (xor_ln117_fu_934_p2 | ap_phi_mux_frame_flag_phi_fu_397_p4);

assign or_ln117_fu_928_p2 = (icmp_ln117_fu_922_p2 | ap_phi_mux_frame_flag_phi_fu_397_p4);

assign p_Result_26_fu_879_p5 = {{p_Val2_1_fu_280[639:64]}, {i_axiu_stream_data_TDATA}};

assign p_Result_27_fu_892_p5 = {{p_Val2_s_fu_276[89:9]}, {p_Result_28_fu_637_p3}};

assign p_Result_28_fu_637_p3 = {{i_axiu_stream_data_TLAST}, {i_axiu_stream_data_TKEEP}};

assign p_Result_29_fu_827_p5 = {{p_Val2_1_fu_280[639:128]}, {i_axiu_stream_data_TDATA}, {p_Val2_1_fu_280[63:0]}};

assign p_Result_30_fu_840_p5 = {{p_Val2_s_fu_276[89:18]}, {p_Result_28_fu_637_p3}, {p_Val2_s_fu_276[8:0]}};

assign p_Result_31_fu_801_p5 = {{p_Val2_1_fu_280[639:192]}, {i_axiu_stream_data_TDATA}, {p_Val2_1_fu_280[127:0]}};

assign p_Result_32_fu_814_p5 = {{p_Val2_s_fu_276[89:27]}, {p_Result_28_fu_637_p3}, {p_Val2_s_fu_276[17:0]}};

assign p_Result_33_fu_775_p5 = {{p_Val2_1_fu_280[639:256]}, {i_axiu_stream_data_TDATA}, {p_Val2_1_fu_280[191:0]}};

assign p_Result_34_fu_788_p5 = {{p_Val2_s_fu_276[89:36]}, {p_Result_28_fu_637_p3}, {p_Val2_s_fu_276[26:0]}};

assign p_Result_35_fu_749_p5 = {{p_Val2_1_fu_280[639:320]}, {i_axiu_stream_data_TDATA}, {p_Val2_1_fu_280[255:0]}};

assign p_Result_36_fu_762_p5 = {{p_Val2_s_fu_276[89:45]}, {p_Result_28_fu_637_p3}, {p_Val2_s_fu_276[35:0]}};

assign p_Result_37_fu_723_p5 = {{p_Val2_1_fu_280[639:384]}, {i_axiu_stream_data_TDATA}, {p_Val2_1_fu_280[319:0]}};

assign p_Result_38_fu_736_p5 = {{p_Val2_s_fu_276[89:54]}, {p_Result_28_fu_637_p3}, {p_Val2_s_fu_276[44:0]}};

assign p_Result_39_fu_697_p5 = {{p_Val2_1_fu_280[639:448]}, {i_axiu_stream_data_TDATA}, {p_Val2_1_fu_280[383:0]}};

assign p_Result_40_fu_710_p5 = {{p_Val2_s_fu_276[89:63]}, {p_Result_28_fu_637_p3}, {p_Val2_s_fu_276[53:0]}};

assign p_Result_41_fu_671_p5 = {{p_Val2_1_fu_280[639:512]}, {i_axiu_stream_data_TDATA}, {p_Val2_1_fu_280[447:0]}};

assign p_Result_42_fu_684_p5 = {{p_Val2_s_fu_276[89:72]}, {p_Result_28_fu_637_p3}, {p_Val2_s_fu_276[62:0]}};

assign p_Result_43_fu_645_p5 = {{p_Val2_1_fu_280[639:576]}, {i_axiu_stream_data_TDATA}, {p_Val2_1_fu_280[511:0]}};

assign p_Result_44_fu_658_p5 = {{p_Val2_s_fu_276[89:81]}, {p_Result_28_fu_637_p3}, {p_Val2_s_fu_276[71:0]}};

assign p_Result_45_fu_853_p5 = {{i_axiu_stream_data_TDATA}, {p_Val2_1_fu_280[575:0]}};

assign p_Result_46_fu_866_p5 = {{p_Result_28_fu_637_p3}, {p_Val2_s_fu_276[80:0]}};

assign src_ip_match_fu_1012_p2 = (icmp_ln1019_fu_1007_p2 | cmp_i_i421);

assign src_port_match_fu_1032_p2 = (icmp_ln1019_2_fu_1027_p2 | cmp_i_i403);

assign tmp_1_fu_912_p4 = {{ap_phi_mux_element_cnt_1_phi_fu_477_p4[7:3]}};

assign tmp_nbreadreq_fu_332_p6 = i_axiu_stream_data_TVALID;

assign xor_ln117_fu_934_p2 = (icmp_ln117_fu_922_p2 ^ 1'd1);

assign zext_ln998_1_fu_1236_p1 = mark_data_V_fu_1226_p4;

assign zext_ln998_fu_1221_p1 = batch_data_V_fu_1211_p4;

endmodule //yusur_udp_filter_yusur_udp_filter_Pipeline_LOOP_WORKING
