set SynModuleInfo {
  {SRCNAME Block_entry60_proc3 MODELNAME Block_entry60_proc3 RTLNAME yusur_hash_allocation_Block_entry60_proc3
    SUBMODULES {
      {MODELNAME yusur_hash_allocation_regslice_both RTLNAME yusur_hash_allocation_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME yusur_hash_allocation_regslice_both_U}
    }
  }
  {SRCNAME Loop_LOOP_READ_AND_DRAIN_proc4 MODELNAME Loop_LOOP_READ_AND_DRAIN_proc4 RTLNAME yusur_hash_allocation_Loop_LOOP_READ_AND_DRAIN_proc4
    SUBMODULES {
      {MODELNAME yusur_hash_allocation_flow_control_loop_pipe RTLNAME yusur_hash_allocation_flow_control_loop_pipe BINDTYPE interface TYPE internal_upc_flow_control INSTNAME yusur_hash_allocation_flow_control_loop_pipe_U}
    }
  }
  {SRCNAME Loop_LOOP_CALC_proc MODELNAME Loop_LOOP_CALC_proc RTLNAME yusur_hash_allocation_Loop_LOOP_CALC_proc
    SUBMODULES {
      {MODELNAME yusur_hash_allocation_mux_83_8_1_1 RTLNAME yusur_hash_allocation_mux_83_8_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME yusur_hash_allocation_mul_8s_8s_8_1_1 RTLNAME yusur_hash_allocation_mul_8s_8s_8_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Loop_LOOP_OUTPUT_ALL_proc MODELNAME Loop_LOOP_OUTPUT_ALL_proc RTLNAME yusur_hash_allocation_Loop_LOOP_OUTPUT_ALL_proc}
  {SRCNAME yusur_hash_allocation MODELNAME yusur_hash_allocation RTLNAME yusur_hash_allocation IS_TOP 1
    SUBMODULES {
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7756_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6755_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5754_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4753_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3752_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2751_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1750_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0749_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7747_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6746_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5745_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4744_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3743_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2742_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1741_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0740_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7738_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6737_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5736_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4735_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3734_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2733_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1732_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0731_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7729_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6728_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5727_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4726_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3725_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2724_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1723_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0722_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7720_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6719_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5718_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4717_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3716_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2715_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1714_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0713_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7711_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6710_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5709_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4708_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3707_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2706_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1705_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0704_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7702_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6701_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5700_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4699_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3698_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2697_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1696_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0695_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7693_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6692_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5691_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4690_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3689_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2688_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1687_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0686_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7628_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6627_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5626_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4625_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3624_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2623_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1622_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0621_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7619_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6618_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5617_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4616_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3615_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2614_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1613_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0612_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7610_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6609_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5608_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4607_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3606_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2605_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1604_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0603_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7601_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6600_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5599_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4598_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3597_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2596_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1595_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0594_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7592_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6591_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5590_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4589_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3588_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2587_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1586_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0585_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7583_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6582_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5581_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4580_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3579_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2578_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1577_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0576_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7574_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6573_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5572_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4571_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3570_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2569_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1568_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0567_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d3_S RTLNAME yusur_hash_allocation_fifo_w8_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d3_S RTLNAME yusur_hash_allocation_fifo_w8_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc62_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d3_S RTLNAME yusur_hash_allocation_fifo_w8_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc63_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d3_S RTLNAME yusur_hash_allocation_fifo_w8_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc64_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d3_S RTLNAME yusur_hash_allocation_fifo_w8_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc65_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d3_S RTLNAME yusur_hash_allocation_fifo_w8_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc66_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d3_S RTLNAME yusur_hash_allocation_fifo_w8_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc67_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d3_S RTLNAME yusur_hash_allocation_fifo_w8_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc68_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7765_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6764_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5763_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4762_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3761_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2760_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1759_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0758_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7685_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6684_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5683_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4682_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3681_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2680_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1679_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0678_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7677_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6676_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5675_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4674_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3673_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2672_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1671_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0670_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7669_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6668_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5667_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4666_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3665_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2664_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1663_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0662_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7661_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6660_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5659_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4658_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3657_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2656_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1655_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0654_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7653_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6652_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5651_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4650_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3649_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2648_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1647_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0646_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7645_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6644_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5643_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4642_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3641_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2640_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1639_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0638_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_7637_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_6636_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_5635_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_4634_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_3633_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_2632_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_1631_loc_channel_U}
      {MODELNAME yusur_hash_allocation_fifo_w8_d2_S RTLNAME yusur_hash_allocation_fifo_w8_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mux_case_0630_loc_channel_U}
    }
  }
}
